#!/usr/bin/env bash
# dispatch-quality-report.sh — INFRA-335 — generate a markdown summary of
# subagent dispatch outcomes from chump_improvement_targets telemetry.
#
# Background (META-025): subagent self-ship rate measured 25-33% across
# both this-session and historical telemetry. Work-quality is high; ship-
# stage hand-off is the bottleneck. This report is the measurement loop
# that answers "is the situation getting better?" without operator polling.
#
# What the report covers:
#   - Outcome split (shipped / killed / stalled / other) with counts and pct
#   - Average duration per outcome
#   - Stall-cause breakdown (depends on INFRA-336 populating notes= field;
#     pre-INFRA-336 stalls show as "unknown")
#   - Top-5 gaps by stall count
#   - Backend split (claude vs chump-local, per COG-025)
#
# Output: docs/audits/DISPATCH_QUALITY_<YYYY-MM-DD>.md (overwritten daily).
#
# Usage:
#   scripts/audit/dispatch-quality-report.sh                # write to default path
#   scripts/audit/dispatch-quality-report.sh --stdout       # print to stdout
#   scripts/audit/dispatch-quality-report.sh --since 7d     # restrict to last 7 days
#   scripts/audit/dispatch-quality-report.sh --db <path>    # override db path (tests)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DB_PATH="${CHUMP_DISPATCH_DB:-$REPO_ROOT/sessions/chump_memory.db}"
OUTPUT="default"
SINCE=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --stdout) OUTPUT="stdout"; shift ;;
        --since)  SINCE="$2"; shift 2 ;;
        --db)     DB_PATH="$2"; shift 2 ;;
        --help|-h)
            sed -n '2,/^$/p' "$0" | sed 's/^# \?//'
            exit 0
            ;;
        *) echo "unknown arg: $1" >&2; exit 2 ;;
    esac
done

if [[ ! -f "$DB_PATH" ]]; then
    echo "ERROR: database not found at $DB_PATH" >&2
    echo "  (set CHUMP_DISPATCH_DB or pass --db <path>)" >&2
    exit 1
fi

# Compute SINCE filter for SQL.
since_clause=""
if [[ -n "$SINCE" ]]; then
    case "$SINCE" in
        *h) hours="${SINCE%h}";   since_clause="AND created_at >= datetime('now', '-${hours} hours')" ;;
        *d) days="${SINCE%d}";    since_clause="AND created_at >= datetime('now', '-${days} days')" ;;
        *)  echo "unrecognized --since '$SINCE'; use 1h / 7d" >&2; exit 2 ;;
    esac
fi

REPORT_DATE="$(date +%Y-%m-%d)"

# Build the report into a tempfile, then either print or move to dest.
TMP="$(mktemp -t chump-dispatch-report-XXXXXX.md)"
trap 'rm -f "$TMP"' EXIT

{
    echo "# Dispatch Quality Report — $REPORT_DATE"
    echo
    echo "> Auto-generated by \`scripts/audit/dispatch-quality-report.sh\` (INFRA-335)."
    echo "> Source: \`$DB_PATH\` (\`chump_improvement_targets\` table, rows where \`directive LIKE 'dispatched%'\`)."
    [[ -n "$SINCE" ]] && echo "> Window: last $SINCE."
    echo
    echo "## TL;DR"
    echo

    sqlite3 "$DB_PATH" "
        SELECT
          CASE
            WHEN directive LIKE '%outcome=shipped%' OR directive LIKE '%outcome=success%' THEN 'shipped'
            WHEN directive LIKE '%outcome=race_abandoned%'                                THEN 'race_abandoned'
            WHEN directive LIKE '%outcome=killed%'                                        THEN 'killed'
            WHEN directive LIKE '%outcome=stalled%'                                       THEN 'stalled'
            WHEN directive LIKE '%outcome=failed%'                                        THEN 'failed'
            ELSE 'other'
          END AS outcome,
          COUNT(*) AS n,
          ROUND(AVG(CAST(SUBSTR(directive, INSTR(directive, 'duration_s=')+11, 6) AS INT)), 0) AS avg_dur_s
        FROM chump_improvement_targets
        WHERE directive LIKE 'dispatched%' $since_clause
        GROUP BY outcome
        ORDER BY n DESC;
    " | python3 -c "
import sys
total = 0
rows = []
for line in sys.stdin:
    line = line.strip()
    if not line: continue
    parts = line.split('|')
    if len(parts) < 3: continue
    outcome, n, dur = parts[0], int(parts[1]), parts[2]
    rows.append((outcome, n, dur))
    total += n
if total == 0:
    print('| outcome | n | pct | avg duration |')
    print('|---|---|---|---|')
    print('| _no rows_ | 0 | – | – |')
else:
    print('| outcome | n | pct | avg duration |')
    print('|---|---|---|---|')
    for outcome, n, dur in sorted(rows, key=lambda r: -r[1]):
        pct = round(100 * n / total, 1)
        try:
            dur_min = round(float(dur) / 60, 1)
        except (ValueError, TypeError):
            dur_min = 0
        print(f'| {outcome} | {n} | {pct}% | {dur_min} min |')
    shipped = next((r[1] for r in rows if r[0] == 'shipped'), 0)
    abandoned = next((r[1] for r in rows if r[0] == 'race_abandoned'), 0)
    # self-ship denominator excludes race_abandoned (coordinated cede is not
    # a failure; including it would deflate the rate unfairly — INFRA-394).
    denom = total - abandoned
    pct = round(100 * shipped / denom, 1) if denom > 0 else 0.0
    print()
    print(f'**Self-ship rate: {pct}%** (target ≥ 70% per META-025; excludes {abandoned} race_abandoned)')
"

    echo
    echo "## Top stalled gaps"
    echo
    stalled_count=$(sqlite3 "$DB_PATH" "SELECT COUNT(*) FROM chump_improvement_targets WHERE directive LIKE '%outcome=stalled%' $since_clause;")
    if [[ "$stalled_count" -eq 0 ]]; then
        echo "_No stalled rows in window._"
    else
        sqlite3 "$DB_PATH" "
            SELECT
              SUBSTR(directive, INSTR(directive, 'gap=')+4, 12) AS gap_id,
              COUNT(*) AS stall_count,
              ROUND(AVG(CAST(SUBSTR(directive, INSTR(directive, 'duration_s=')+11, 6) AS INT)) / 60, 1) AS avg_min
            FROM chump_improvement_targets
            WHERE directive LIKE '%outcome=stalled%' $since_clause
            GROUP BY gap_id
            ORDER BY stall_count DESC, avg_min DESC
            LIMIT 5;
        " | awk -F'|' 'BEGIN { print "| gap | stalls | avg duration |"; print "|---|---|---|" }
                       NF == 3 { print "| " $1 " | " $2 " | " $3 " min |" }'
    fi

    echo
    echo "## Stall-cause breakdown"
    echo
    echo "_Pre-INFRA-336, stall causes are unclassified. Once INFRA-336 lands, worker.sh writes \`notes=cause:<bot-merge-hung|cargo-build-timeout|...|unknown>\`._"
    echo
    sqlite3 "$DB_PATH" "
        SELECT
          CASE
            WHEN directive LIKE '%notes=cause:bot-merge-hung%'         THEN 'bot-merge-hung'
            WHEN directive LIKE '%notes=cause:cargo-build-timeout%'    THEN 'cargo-build-timeout'
            WHEN directive LIKE '%notes=cause:API-credit-exhausted%'   THEN 'API-credit-exhausted'
            WHEN directive LIKE '%notes=cause:chump-binary-wedge%'     THEN 'chump-binary-wedge'
            WHEN directive LIKE '%notes=cause:%'                       THEN 'other-classified'
            ELSE 'unknown (pre-INFRA-336)'
          END AS cause,
          COUNT(*) AS n
        FROM chump_improvement_targets
        WHERE directive LIKE '%outcome=stalled%' $since_clause
        GROUP BY cause
        ORDER BY n DESC;
    " | awk -F'|' 'BEGIN { print "| cause | n |"; print "|---|---|" }
                   NF == 2 { print "| " $1 " | " $2 " |" }'

    echo
    echo "## Backend split (COG-025)"
    echo
    sqlite3 "$DB_PATH" "
        SELECT
          CASE
            WHEN directive LIKE '%backend=claude%'      THEN 'claude'
            WHEN directive LIKE '%backend=chump-local%' THEN 'chump-local'
            ELSE 'unspecified'
          END AS backend,
          CASE
            WHEN directive LIKE '%outcome=shipped%'        THEN 'shipped'
            WHEN directive LIKE '%outcome=race_abandoned%' THEN 'race_abandoned'
            WHEN directive LIKE '%outcome=killed%'         THEN 'killed'
            WHEN directive LIKE '%outcome=stalled%'        THEN 'stalled'
            ELSE 'other'
          END AS outcome,
          COUNT(*) AS n
        FROM chump_improvement_targets
        WHERE directive LIKE 'dispatched%' $since_clause
        GROUP BY backend, outcome
        ORDER BY backend, outcome;
    " | awk -F'|' 'BEGIN { print "| backend | outcome | n |"; print "|---|---|---|" }
                   NF == 3 { print "| " $1 " | " $2 " | " $3 " |" }'

    echo
    echo "---"
    echo
    echo "## Action items (auto-flagged)"
    echo
    stall_pct=$(sqlite3 "$DB_PATH" "
        SELECT
          CASE WHEN total = 0 THEN 0 ELSE ROUND(100.0 * stalled / total, 1) END
        FROM (
          SELECT
            SUM(CASE WHEN directive LIKE '%outcome=stalled%' THEN 1 ELSE 0 END) AS stalled,
            COUNT(*) AS total
          FROM chump_improvement_targets
          WHERE directive LIKE 'dispatched%' $since_clause
        );
    ")
    if [[ -n "$stall_pct" ]] && python3 -c "import sys; sys.exit(0 if float('$stall_pct') > 50.0 else 1)"; then
        echo "- 🚨 Stall rate is ${stall_pct}% (>50% threshold) — investigate INFRA-275 / INFRA-301 health, run \`scripts/dev/chump-binary-unwedge.sh\` on dispatcher hosts."
    elif [[ -n "$stall_pct" ]] && python3 -c "import sys; sys.exit(0 if float('$stall_pct') > 30.0 else 1)"; then
        echo "- ⚠️  Stall rate is ${stall_pct}% (above META-025 target of <30%). Review INFRA-332 shipping-epilogue adoption."
    else
        echo "- ✅ Stall rate within acceptable range (${stall_pct}%)."
    fi

    unknown_pct=$(sqlite3 "$DB_PATH" "
        SELECT
          CASE WHEN total = 0 THEN 0 ELSE ROUND(100.0 * unknown / total, 1) END
        FROM (
          SELECT
            SUM(CASE WHEN directive LIKE '%outcome=stalled%' AND directive NOT LIKE '%notes=cause:%' THEN 1 ELSE 0 END) AS unknown,
            SUM(CASE WHEN directive LIKE '%outcome=stalled%' THEN 1 ELSE 0 END) AS total
          FROM chump_improvement_targets
          WHERE directive LIKE 'dispatched%' $since_clause
        );
    ")
    if [[ -n "$unknown_pct" ]] && python3 -c "import sys; sys.exit(0 if float('$unknown_pct') > 50.0 else 1)"; then
        echo "- ⚠️  ${unknown_pct}% of stalls have no cause classification — INFRA-336 not landed yet, or worker.sh classification regression."
    fi

    echo
    echo "_Generated $(date -u +%Y-%m-%dT%H:%M:%SZ). Re-run via \`scripts/audit/dispatch-quality-report.sh\`._"
} > "$TMP"

if [[ "$OUTPUT" == "stdout" ]]; then
    cat "$TMP"
else
    DEST="$REPO_ROOT/docs/audits/DISPATCH_QUALITY_${REPORT_DATE}.md"
    mkdir -p "$(dirname "$DEST")"
    mv "$TMP" "$DEST"
    trap - EXIT
    echo "wrote $DEST"
fi
