#!/usr/bin/env bash
# scripts/audit/run-all.sh — INFRA-044
#
# Dispatches static-analysis tools (cargo-deny, cargo-audit, cargo-udeps,
# cargo-machete, lychee, cargo clippy --pedantic) and writes a single
# aggregated findings document with severity tiers.
#
# Usage:
#   scripts/audit/run-all.sh                 # write to docs/audit/findings-YYYY-MM-DD.md
#   scripts/audit/run-all.sh --out PATH      # custom output
#   scripts/audit/run-all.sh --quick         # skip the slow tools (udeps, clippy-pedantic)
#
# Missing tools are reported and skipped — the script never aborts on a
# missing tool. A non-zero exit happens only on critical findings
# (CVE advisory, license conflict) so CI can gate on them.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

OUT=""
QUICK=0
while [[ $# -gt 0 ]]; do
    case "$1" in
        --out) OUT="$2"; shift 2 ;;
        --quick) QUICK=1; shift ;;
        -h|--help) sed -n '2,16p' "$0"; exit 0 ;;
        *) echo "unknown arg: $1" >&2; exit 2 ;;
    esac
done

DATE="$(date +%Y-%m-%d)"
: "${OUT:=docs/audit/findings-$DATE.md}"
mkdir -p "$(dirname "$OUT")"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

CRITICAL_COUNT=0
HIGH_COUNT=0
MEDIUM_COUNT=0

section() {
    printf '\n## %s\n\n' "$1" >> "$OUT"
}

have() { command -v "$1" >/dev/null 2>&1; }

record_skip() {
    local tool="$1" why="$2"
    printf '**Skipped** — %s.\n\n' "$why" >> "$OUT"
    printf '> Install: `%s`\n' "$3" >> "$OUT"
}

# Header
{
    printf '# Chump audit findings — %s\n\n' "$DATE"
    printf 'Generated by `scripts/audit/run-all.sh` (INFRA-044). '
    printf 'Each section summarises output from one static-analysis tool. '
    printf 'Severity tiers: **Critical** (CVE / license conflict / security) → gap filing required; '
    printf '**High** (broken builds, unused deps, pedantic errors); '
    printf '**Medium** (link rot, style warnings); '
    printf '**Info** (stats, advisories noted but not actionable).\n'
} > "$OUT"

# ---- cargo-deny (bans, licenses, advisories, sources) ----
section "cargo-deny"
if have cargo-deny; then
    if cargo deny check --format human 2>"$TMP/deny.err" >"$TMP/deny.out"; then
        printf '**OK** — no advisories, license conflicts, or banned crates.\n\n' >> "$OUT"
    else
        printf '**Findings** (see raw output below):\n\n```\n' >> "$OUT"
        cat "$TMP/deny.out" "$TMP/deny.err" >> "$OUT" 2>/dev/null || true
        printf '```\n\n' >> "$OUT"
        # heuristic: "error[" or "license not allowed" bumps critical
        if grep -qE '(error\[|license.*not.*allowed|vulnerability)' "$TMP/deny.out" "$TMP/deny.err" 2>/dev/null; then
            CRITICAL_COUNT=$((CRITICAL_COUNT + 1))
            printf '**Severity: Critical** — one or more advisory / license / ban violations.\n\n' >> "$OUT"
        else
            HIGH_COUNT=$((HIGH_COUNT + 1))
            printf '**Severity: High**\n\n' >> "$OUT"
        fi
    fi
else
    record_skip cargo-deny "cargo-deny not installed" "cargo install --locked cargo-deny"
fi

# ---- cargo-audit (RustSec CVE database) ----
section "cargo-audit"
if have cargo-audit; then
    if cargo audit --json >"$TMP/audit.json" 2>"$TMP/audit.err"; then
        printf '**OK** — no known vulnerabilities in the dependency tree.\n\n' >> "$OUT"
    else
        # cargo-audit exits 1 when vulnerabilities found; still parseable
        ADV_COUNT=$(grep -c '"advisory"' "$TMP/audit.json" 2>/dev/null || echo 0)
        printf '**%s vulnerability advisor(ies)** reported.\n\n```\n' "$ADV_COUNT" >> "$OUT"
        cat "$TMP/audit.err" >> "$OUT" 2>/dev/null || true
        # Also include a trimmed summary from the JSON
        if have jq; then
            jq -r '.vulnerabilities.list[]? | "\(.advisory.id) \(.advisory.package): \(.advisory.title)"' "$TMP/audit.json" >> "$OUT" 2>/dev/null || true
        fi
        printf '```\n\n' >> "$OUT"
        if [[ "$ADV_COUNT" -gt 0 ]]; then
            CRITICAL_COUNT=$((CRITICAL_COUNT + ADV_COUNT))
            printf '**Severity: Critical** — CVE in dependency tree.\n\n' >> "$OUT"
        fi
    fi
else
    record_skip cargo-audit "cargo-audit not installed" "cargo install --locked cargo-audit"
fi

# ---- cargo-udeps (unused dependencies) ----
section "cargo-udeps"
if [[ "$QUICK" == "1" ]]; then
    printf '**Skipped** — `--quick` mode.\n\n' >> "$OUT"
elif have cargo-udeps; then
    # cargo-udeps requires nightly
    if cargo +nightly udeps --all-targets 2>"$TMP/udeps.err" >"$TMP/udeps.out"; then
        printf '**OK** — no unused dependencies.\n\n' >> "$OUT"
    else
        printf '**Findings:**\n\n```\n' >> "$OUT"
        cat "$TMP/udeps.out" "$TMP/udeps.err" >> "$OUT" 2>/dev/null || true
        printf '```\n\n' >> "$OUT"
        HIGH_COUNT=$((HIGH_COUNT + 1))
        printf '**Severity: High** — unused deps bloat the build; remove them.\n\n' >> "$OUT"
    fi
else
    record_skip cargo-udeps "cargo-udeps not installed (requires nightly)" "cargo install --locked cargo-udeps"
fi

# ---- cargo-machete (faster udeps alternative, stable toolchain) ----
section "cargo-machete"
if have cargo-machete; then
    if cargo machete 2>"$TMP/mach.err" >"$TMP/mach.out"; then
        printf '**OK** — no unused dependencies.\n\n' >> "$OUT"
    else
        printf '**Findings:**\n\n```\n' >> "$OUT"
        cat "$TMP/mach.out" "$TMP/mach.err" >> "$OUT" 2>/dev/null || true
        printf '```\n\n' >> "$OUT"
        HIGH_COUNT=$((HIGH_COUNT + 1))
        printf '**Severity: High**\n\n' >> "$OUT"
    fi
else
    record_skip cargo-machete "cargo-machete not installed" "cargo install --locked cargo-machete"
fi

# ---- lychee (doc link rot) ----
section "lychee"
if have lychee; then
    # Check docs/ and book/src/ for broken links; offline by default (no network)
    if lychee --offline --no-progress 'docs/**/*.md' 'book/src/**/*.md' 'README.md' 'AGENTS.md' 'CLAUDE.md' 2>"$TMP/lychee.err" >"$TMP/lychee.out"; then
        printf '**OK** — no broken doc links (offline check).\n\n' >> "$OUT"
    else
        printf '**Findings:**\n\n```\n' >> "$OUT"
        tail -60 "$TMP/lychee.out" >> "$OUT" 2>/dev/null || true
        printf '```\n\n' >> "$OUT"
        MEDIUM_COUNT=$((MEDIUM_COUNT + 1))
        printf '**Severity: Medium** — doc link rot degrades onboarding.\n\n' >> "$OUT"
    fi
else
    record_skip lychee "lychee not installed" "cargo install --locked lychee"
fi

# ---- cargo clippy --pedantic ----
section "cargo clippy --pedantic"
if [[ "$QUICK" == "1" ]]; then
    printf '**Skipped** — `--quick` mode.\n\n' >> "$OUT"
else
    # Only `--bin chump` to keep runtime bounded; workspace-wide pedantic is too noisy for a weekly run.
    if cargo clippy --bin chump -- -W clippy::pedantic 2>"$TMP/clippy.err" >"$TMP/clippy.out"; then
        W_COUNT=$(grep -c '^warning' "$TMP/clippy.err" 2>/dev/null || echo 0)
        if [[ "$W_COUNT" -gt 0 ]]; then
            printf '**%s pedantic warnings** — see raw output for details:\n\n```\n' "$W_COUNT" >> "$OUT"
            head -80 "$TMP/clippy.err" >> "$OUT"
            printf '```\n\n' >> "$OUT"
            MEDIUM_COUNT=$((MEDIUM_COUNT + 1))
            printf '**Severity: Medium** — pedantic lints are opt-in style guidance.\n\n' >> "$OUT"
        else
            printf '**OK** — no pedantic warnings.\n\n' >> "$OUT"
        fi
    else
        printf '**Build failure** (pedantic compile error):\n\n```\n' >> "$OUT"
        tail -60 "$TMP/clippy.err" >> "$OUT"
        printf '```\n\n' >> "$OUT"
        HIGH_COUNT=$((HIGH_COUNT + 1))
        printf '**Severity: High** — pedantic lints promoted to errors by another flag.\n\n' >> "$OUT"
    fi
fi

# ---- Summary + pending-gap template for critical findings ----
{
    printf '\n'; printf -- '---\n\n## Summary\n\n'
    printf '| Tier | Count |\n|---|---|\n'
    printf '| Critical | %d |\n' "$CRITICAL_COUNT"
    printf '| High | %d |\n' "$HIGH_COUNT"
    printf '| Medium | %d |\n' "$MEDIUM_COUNT"
    printf '\n'
} >> "$OUT"

if [[ "$CRITICAL_COUNT" -gt 0 ]]; then
    {
        printf '## Auto-filed gap candidates\n\n'
        printf '%s critical finding(s) require a new gap. Suggested template:\n\n' "$CRITICAL_COUNT"
        printf '```yaml\n'
        printf -- '- id: SECURITY-NNN            # use scripts/gap-reserve.sh SECURITY "short title"\n'
        printf '  title: Fix critical audit finding from %s\n' "$DATE"
        printf '  domain: infra\n'
        printf '  priority: P1\n'
        printf '  effort: s\n'
        printf '  source_doc: docs/audit/findings-%s.md\n' "$DATE"
        printf '  status: open\n'
        printf '  description: See findings doc for CVE / license details.\n'
        printf '```\n\n'
        printf '> Run `scripts/gap-reserve.sh SECURITY "fix <cve-id>"` to file.\n'
    } >> "$OUT"
fi

echo "[audit] wrote $OUT — critical=$CRITICAL_COUNT high=$HIGH_COUNT medium=$MEDIUM_COUNT"

# Non-zero exit when critical findings present so CI can gate.
if [[ "$CRITICAL_COUNT" -gt 0 ]]; then
    exit 1
fi
exit 0
