#!/usr/bin/env python3
"""Render docker-compose.yml + Caddyfile from apps.conf (one isolated Supabase per app).

Every app gets its own Postgres DATABASE (own auth.users + storage schema) in the one shared
cluster, plus its own GoTrue / PostgREST / Storage containers and its own JWT secret.
Host ports (loopback only): rest 5433N, auth 999N, storage 500N, where N = the app's index.
Run: python3 scripts/render.py   (writes ../docker-compose.yml and ../Caddyfile)
"""
import pathlib
ROOT = pathlib.Path(__file__).resolve().parent.parent
apps = []
for line in (ROOT / "apps.conf").read_text().splitlines():
    line = line.split("#", 1)[0].strip()
    if line:
        app, n, host, site = line.split()
        apps.append(dict(app=app, n=n, host=host, site=site, U=app.upper()))

HDR = """# GENERATED by scripts/render.py from apps.conf. Edit those, not this file.
# Self-hosted Supabase on cuphead: ONE Postgres cluster, ONE database + auth + REST + storage
# stack PER APP (separate user bases). Secrets come from --env-file /srv/supabase-data/.env
# (scripts/gen-secrets.sh + scripts/gen-app-secrets.sh); nothing secret is in this file.
# All host ports bind 127.0.0.1 except Studio (tailnet IP). Public HTTPS = Caddy.

x-slice: &slice
  cgroup_parent: supabase.slice  # MemoryMax=4G guard; systemd-run around compose does NOT reach containers
  restart: unless-stopped

services:
  postgres:
    <<: *slice
    image: supabase/postgres:15.1.1.51
    container_name: supabase_postgres
    oom_score_adj: -800  # product DB is the last thing the kernel/earlyoom should pick
    # max_connections etc. are SERVER flags (-c), not initdb flags. Overriding `command`
    # drops the image's listen_addresses, so it is set here too.
    command: >-
      postgres
      -c listen_addresses=*
      -c max_connections=200
      -c shared_buffers=256MB
      -c shared_preload_libraries=pg_stat_statements
    volumes:
      - /srv/supabase-data/postgres:/var/lib/postgresql/data
      # zz-* runs AFTER the image's init-scripts (roles, auth + storage schemas), then clones
      # that pristine `postgres` DB into one database per app.
      - ./postgres-init-apps.sh:/docker-entrypoint-initdb.d/zz-apps.sh:ro
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "127.0.0.1:54322:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
"""

APP = """
  # ---------------- {app} ({host}) ----------------
  auth_{app}:
    <<: *slice
    image: supabase/gotrue:v2.119.0
    container_name: supabase_auth_{app}
    depends_on: {{ postgres: {{ condition: service_healthy }} }}
    environment:
      GOTRUE_API_HOST: "0.0.0.0"
      GOTRUE_API_PORT: "9999"
      API_EXTERNAL_URL: "https://{host}"
      GOTRUE_DB_DRIVER: postgres
      # search_path=auth is required: without it GoTrue migrates into `public` and signup 500s.
      GOTRUE_DB_DATABASE_URL: "postgres://postgres:${{POSTGRES_PASSWORD}}@postgres:5432/{app}?sslmode=disable&search_path=auth"
      GOTRUE_SITE_URL: "{site}"
      GOTRUE_URI_ALLOW_LIST: "{site},{site}/**,http://localhost:3000,http://localhost:3000/**"
      GOTRUE_DISABLE_SIGNUP: "false"
      GOTRUE_JWT_SECRET: "${{JWT_SECRET_{U}}}"
      GOTRUE_JWT_EXP: "3600"
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_PASSWORD_MIN_LENGTH: "8"
      # No SMTP on this box yet: auto-confirm email signups (dev data; revisit before real users).
      GOTRUE_MAILER_AUTOCONFIRM: "${{GOTRUE_MAILER_AUTOCONFIRM:-true}}"
      # Google sign-in: this app's OWN OAuth client. Off until real credentials are in the env file.
      GOTRUE_EXTERNAL_GOOGLE_ENABLED: "${{GOOGLE_ENABLED_{U}:-false}}"
      GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID: "${{GOOGLE_CLIENT_ID_{U}}}"
      GOTRUE_EXTERNAL_GOOGLE_SECRET: "${{GOOGLE_CLIENT_SECRET_{U}}}"
      GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI: "https://{host}/auth/v1/callback"
    ports: ["127.0.0.1:999{n}:9999"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9999/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  rest_{app}:
    <<: *slice
    image: postgrest/postgrest:v11.2.0
    container_name: supabase_rest_{app}
    depends_on: {{ postgres: {{ condition: service_healthy }} }}
    environment:
      PGRST_DB_URI: "postgres://authenticator:${{POSTGRES_PASSWORD}}@postgres:5432/{app}"
      PGRST_DB_SCHEMAS: "public,graphql_public"  # hosted parity: never expose storage/auth via REST
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: "${{JWT_SECRET_{U}}}"
      PGRST_DB_USE_LEGACY_GUCS: "false"
      PGRST_MAX_ROWS: "1000"
    ports: ["127.0.0.1:5433{n}:3000"]

  storage_{app}:
    <<: *slice
    image: supabase/storage-api:v0.46.4
    container_name: supabase_storage_{app}
    depends_on:
      postgres: {{ condition: service_healthy }}
      rest_{app}: {{ condition: service_started }}
    volumes:
      - /srv/supabase-data/storage/{app}:/var/lib/storage
    environment:
      ANON_KEY: "${{ANON_KEY_{U}}}"
      SERVICE_KEY: "${{SERVICE_ROLE_KEY_{U}}}"
      POSTGREST_URL: "http://rest_{app}:3000"
      PGRST_JWT_SECRET: "${{JWT_SECRET_{U}}}"
      DATABASE_URL: "postgres://supabase_storage_admin:${{POSTGRES_PASSWORD}}@postgres:5432/{app}"
      FILE_SIZE_LIMIT: "52428800"
      STORAGE_BACKEND: file
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
      TENANT_ID: {app}
      REGION: local
      GLOBAL_S3_BUCKET: {app}
    ports: ["127.0.0.1:500{n}:5000"]
"""

TAIL = """
  # Admin UI: tailnet-only. pg-meta can switch database from the Studio UI connection string;
  # it defaults to the `postgres` DB (the pristine template, holds no app data).
  meta:
    <<: *slice
    image: supabase/postgres-meta:v0.68.0
    container_name: supabase_meta
    depends_on: { postgres: { condition: service_healthy } }
    environment:
      PG_META_PORT: "8080"
      PG_META_DB_HOST: postgres
      PG_META_DB_PORT: "5432"
      PG_META_DB_NAME: postgres
      PG_META_DB_USER: postgres
      PG_META_DB_PASSWORD: "${POSTGRES_PASSWORD}"

  studio:
    <<: *slice
    image: supabase/studio:latest
    container_name: supabase_studio
    depends_on: { postgres: { condition: service_healthy } }
    ports:
      - "${STUDIO_BIND_ADDR:-127.0.0.1}:${STUDIO_HOST_PORT:-8000}:3000"
    environment:
      STUDIO_PG_META_URL: "http://meta:8080"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      DEFAULT_ORGANIZATION_NAME: cuphead
    # studio:latest no longer serves /api/platform/profile with 200; check the root instead.
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://'+require('os').hostname()+':3000/',r=>process.exit(r.statusCode<400?0:1)).on('error',()=>process.exit(1))"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  default:
    name: supabase_default
"""

compose = HDR + "".join(APP.format(**a) for a in apps) + TAIL
(ROOT / "docker-compose.yml").write_text(compose)

caddy = ["""# GENERATED by scripts/render.py from apps.conf. Edit those, not this file.
# Caddy (arm64, official apt repo) terminates TLS (Let's Encrypt) for each app's API host and
# routes Supabase paths to THAT app's own services. Kong parity: REST + Storage refuse requests
# with no apikey/Authorization; Auth is exempt (OAuth redirects arrive without one). The check
# sits INSIDE each handle_path because Caddy orders handle_path before a site-level respond.

(supabase_app) {
\t@nokey {
\t\tnot header apikey *
\t\tnot header Authorization *
\t}
\thandle_path /rest/v1/* {
\t\trespond @nokey `{"message":"No API key found in request"}` 401
\t\treverse_proxy 127.0.0.1:5433{args[0]}
\t}
\thandle_path /auth/v1/* {
\t\treverse_proxy 127.0.0.1:999{args[0]}
\t}
\t@storage_nokey {
\t\tnot header apikey *
\t\tnot header Authorization *
\t\tnot path /object/public/*
\t}
\thandle_path /storage/v1/* {
\t\trespond @storage_nokey `{"message":"No API key found in request"}` 401
\t\treverse_proxy 127.0.0.1:500{args[0]}
\t}
\thandle {
\t\trespond "supabase (cuphead) - use /rest/v1, /auth/v1, /storage/v1" 200
\t}
}
"""]
for a in apps:
    caddy.append(f"\n# {a['app']}\n{a['host']} {{\n\timport supabase_app {a['n']}\n}}\n")
(ROOT / "Caddyfile").write_text("".join(caddy))
print("rendered", len(apps), "apps")
