#!/usr/bin/env bash
# generate-organ-registry.sh — INFRA-7586 (INFRA-3648 slice).
#
# WHY THIS EXISTS. scripts/ops/node-organ-manifest.txt (INFRA-7327) declares
# CJ's 9 process-level organs, but it is a HAND-AUTHORED copy of
# install-node-housekeeping.sh's ORGANS table (the comment there literally
# says "keep the two in sync if that table changes") — a second grammar for
# the same source of truth, one edit away from drifting silently the same
# way chump-backlog-sync-writer.timer sat undeclared for 21 days (CREDIBLE-292).
# This script closes that gap: it extracts the ORGANS table directly out of
# install-node-housekeeping.sh (no re-typing) and GENERATES
# scripts/ops/organ-registry.txt from it, so the registry can never drift
# from the table that actually installs the organs.
#
# Format mirrors scripts/ops/organ-manifest.txt's enabled/paging_off
# directive syntax:
#   enabled  <name>  launcher=<path>  pgrep=<pattern>  heartbeat=<seconds>  # wraps <script>
#
# Usage:
#   scripts/ops/generate-organ-registry.sh              # regenerate the registry file
#   scripts/ops/generate-organ-registry.sh --stdout      # print, don't write
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SOURCE_FILE="$REPO_ROOT/scripts/setup/install-node-housekeeping.sh"
OUT_FILE="$REPO_ROOT/scripts/ops/organ-registry.txt"

if [ ! -f "$SOURCE_FILE" ]; then
  echo "generate-organ-registry: missing source $SOURCE_FILE" >&2
  exit 1
fi

# Extract the ORGANS="..." table without sourcing the rest of the installer
# (which performs real installs). It's a single ORGANS="...multi-line..."
# assignment terminated by a bare trailing double-quote on the last data
# line (no closing `"` on its own line), so awk tracks start/end explicitly
# rather than relying on a sed range match. Each data line is
# "name|repo-relative-script[ args]|cadence-seconds".
organs_table="$(awk '
  /^ORGANS="/ { sub(/^ORGANS="/, ""); in_organs=1 }
  in_organs {
    if (sub(/"[[:space:]]*$/, "")) { print; in_organs=0; next }
    print
  }
' "$SOURCE_FILE")"

if [ -z "$organs_table" ]; then
  echo "generate-organ-registry: could not extract ORGANS table from $SOURCE_FILE" >&2
  exit 1
fi

render() {
  cat <<'HEADER'
# organ-registry.txt — GENERATED by scripts/ops/generate-organ-registry.sh
# (INFRA-7586, INFRA-3648 slice). Do not hand-edit; re-run the generator
# after changing install-node-housekeeping.sh's ORGANS table.
#
# Sibling of scripts/ops/organ-manifest.txt (systemd units, read by
# organ-reconcile.sh) and scripts/ops/process-organ-registry.txt (raw
# non-systemd background processes, read by process-organ-heal.sh). This
# registry covers CJ's node-housekeeping organs (the "supervisor=nohup"
# loop-wrapped fallback path installed by install-node-housekeeping.sh),
# sourced directly from that installer's ORGANS table so the registry can
# never drift out of sync with what actually gets installed.
#
# Format: one directive per line,
#   "<state>  <name>  launcher=<path>  pgrep=<pattern>  heartbeat=<seconds>  # wraps <tracked-script>"
#
#   state       enabled — this organ must be running.
#   name        short identifier, matches install-node-housekeeping.sh's
#               ORGANS table and its chump-<name> supervised-unit naming.
#   launcher    the self-contained loop-wrapper written by
#               install-node-housekeeping.sh's write_runner() at
#               ~/.chump/organs/<name>.sh.
#   pgrep       the `pgrep -f` match pattern for the live detector. The
#               LAUNCHER path is used (not the wrapped script's own path)
#               because the launcher is what stays resident between
#               wrapped-script invocations.
#   heartbeat   seconds between wrapped-script invocations; 0 means the
#               wrapped script self-loops forever (no external cadence).
HEADER
  echo

  while IFS='|' read -r name script_and_args cadence; do
    [ -z "${name:-}" ] && continue
    script="${script_and_args%% *}"
    launcher="~/.chump/organs/${name}.sh"
    printf 'enabled  %-22s launcher=%-40s pgrep=%-40s heartbeat=%-6s # wraps %s\n' \
      "$name" "$launcher" "$launcher" "$cadence" "$script"
  done <<<"$organs_table"
}

if [ "${1:-}" = "--stdout" ]; then
  render
else
  render > "$OUT_FILE"
  echo "generate-organ-registry: wrote $OUT_FILE"
fi
