#!/usr/bin/env bash
# generate-organ-registry.sh — INFRA-7586 (INFRA-3648 slice).
#
# WHY THIS EXISTS. scripts/ops/node-organ-manifest.txt (INFRA-7327) declares
# CJ's 9 process-level organs, but it is a HAND-AUTHORED copy of
# install-node-housekeeping.sh's ORGANS table (the comment there literally
# says "keep the two in sync if that table changes") — a second grammar for
# the same source of truth, one edit away from drifting silently the same
# way chump-backlog-sync-writer.timer sat undeclared for 21 days (CREDIBLE-292).
# This script closes that gap: it derives the ORGANS table the SAME WAY
# install-node-housekeeping.sh itself does (no re-typing) and GENERATES
# scripts/ops/organ-registry.txt from it, so the registry can never drift
# from the table that actually installs the organs.
#
# INFRA-3648 (roll-call regression found + fixed in this slice): until this
# fix, this script awk-parsed a literal `ORGANS="...heredoc..."` assignment
# out of install-node-housekeeping.sh. INFRA-7766 replaced that heredoc with
# `ORGANS="$(housekeeping_organs_from_manifest "$ORGAN_MANIFEST_FILE")"` (a
# function call, sourced from organ-manifest.txt's `housekeeping=` tokens) —
# the awk pattern silently matched the new one-line assignment as if it were
# a self-terminating single-line table, producing a garbage single "organ"
# whose name was the literal text `$(housekeeping_organs_from_manifest
# "$ORGAN_MANIFEST_FILE")`. test-generate-organ-registry.sh caught this (the
# exact "roll-call fails when a launched organ is absent from the registry"
# class this gap's AC2 calls for) once this slice re-ran it. Fix: call the
# SAME library function the installer calls, instead of parsing the
# installer's source text — there is now exactly one code path that resolves
# the organ roster, not two that can drift apart again.
#
# Format mirrors scripts/ops/organ-manifest.txt's enabled/paging_off
# directive syntax:
#   enabled  <name>  launcher=<path>  pgrep=<pattern>  heartbeat=<seconds>  # wraps <script>
#
# Usage:
#   scripts/ops/generate-organ-registry.sh              # regenerate the registry file
#   scripts/ops/generate-organ-registry.sh --stdout      # print, don't write
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SOURCE_FILE="$REPO_ROOT/scripts/setup/install-node-housekeeping.sh"
ROSTER_LIB="$REPO_ROOT/scripts/ops/lib/node-housekeeping-roster-lib.sh"
ORGAN_MANIFEST_FILE="${CHUMP_ORGAN_MANIFEST:-$REPO_ROOT/scripts/ops/organ-manifest.txt}"
OUT_FILE="$REPO_ROOT/scripts/ops/organ-registry.txt"

if [ ! -f "$SOURCE_FILE" ]; then
  echo "generate-organ-registry: missing source $SOURCE_FILE" >&2
  exit 1
fi

if [ ! -f "$ROSTER_LIB" ]; then
  echo "generate-organ-registry: missing roster lib $ROSTER_LIB" >&2
  exit 1
fi

# shellcheck source=lib/node-housekeeping-roster-lib.sh
. "$ROSTER_LIB"
organs_table="$(housekeeping_organs_from_manifest "$ORGAN_MANIFEST_FILE")"

if [ -z "$organs_table" ]; then
  echo "generate-organ-registry: could not resolve an organ roster (manifest=$ORGAN_MANIFEST_FILE)" >&2
  exit 1
fi

render() {
  cat <<'HEADER'
# organ-registry.txt — GENERATED by scripts/ops/generate-organ-registry.sh
# (INFRA-7586, INFRA-3648 slice). Do not hand-edit; re-run the generator
# after changing install-node-housekeeping.sh's ORGANS table.
#
# Sibling of scripts/ops/organ-manifest.txt (systemd units, read by
# organ-reconcile.sh) and scripts/ops/process-organ-registry.txt (raw
# non-systemd background processes, read by process-organ-heal.sh). This
# registry covers CJ's node-housekeeping organs (the "supervisor=nohup"
# loop-wrapped fallback path installed by install-node-housekeeping.sh),
# sourced directly from that installer's ORGANS table so the registry can
# never drift out of sync with what actually gets installed.
#
# Format: one directive per line,
#   "<state>  <name>  launcher=<path>  pgrep=<pattern>  heartbeat=<seconds>  # wraps <tracked-script>"
#
#   state       enabled — this organ must be running.
#   name        short identifier, matches install-node-housekeeping.sh's
#               ORGANS table and its chump-<name> supervised-unit naming.
#   launcher    the self-contained loop-wrapper written by
#               install-node-housekeeping.sh's write_runner() at
#               ~/.chump/organs/<name>.sh.
#   pgrep       the `pgrep -f` match pattern for the live detector. The
#               LAUNCHER path is used (not the wrapped script's own path)
#               because the launcher is what stays resident between
#               wrapped-script invocations.
#   heartbeat   seconds between wrapped-script invocations; 0 means the
#               wrapped script self-loops forever (no external cadence).
HEADER
  echo

  while IFS='|' read -r name script_and_args cadence; do
    [ -z "${name:-}" ] && continue
    script="${script_and_args%% *}"
    launcher="~/.chump/organs/${name}.sh"
    printf 'enabled  %-22s launcher=%-40s pgrep=%-40s heartbeat=%-6s # wraps %s\n' \
      "$name" "$launcher" "$launcher" "$cadence" "$script"
  done <<<"$organs_table"
}

if [ "${1:-}" = "--stdout" ]; then
  render
else
  render > "$OUT_FILE"
  echo "generate-organ-registry: wrote $OUT_FILE"
fi
