#!/usr/bin/env bash
# test-merge-driver-state-sql.sh — INFRA-310
#
# End-to-end test: simulate the multi-day-rebase scenario where
# .chump/state.sql conflicts on rebase, and verify the custom merge driver
# resolves it cleanly without manual conflict markers.
#
# We don't depend on a real `chump` binary in the fixture — the driver
# accepts CHUMP_BIN env override, so we point it at a stub that writes a
# canonical "regenerated" string. The test is about the *driver wiring*
# (gitattributes + git config + git rebase invocation) — that the
# regeneration logic itself works is covered by chump's own gap-store tests.

set -euo pipefail

PASS=0
FAIL=0
ok() { echo "  PASS: $1"; PASS=$((PASS+1)); }
fail() { echo "  FAIL: $1"; FAIL=$((FAIL+1)); }

echo "=== INFRA-310 .chump/state.sql merge driver test ==="
echo

REPO_ROOT="$(git rev-parse --show-toplevel)"
DRIVER_SCRIPT="$REPO_ROOT/scripts/git/merge-driver-state-sql-regen.sh"
INSTALLER="$REPO_ROOT/scripts/setup/install-merge-drivers.sh"
[ -x "$DRIVER_SCRIPT" ] || { echo "FATAL: driver script missing"; exit 2; }
[ -x "$INSTALLER" ] || { echo "FATAL: installer missing"; exit 2; }

TMPDIR_BASE="$(mktemp -d)"
trap 'rm -rf "$TMPDIR_BASE"' EXIT

# ── Set up a fresh fake repo with the .gitattributes wiring ────────────────
FAKE="$TMPDIR_BASE/repo"
mkdir -p "$FAKE/.chump" "$FAKE/scripts/git" "$FAKE/scripts/setup"
git -C "$FAKE" init -q -b main
git -C "$FAKE" config user.email "test@test.com"
git -C "$FAKE" config user.name "Test"

# Copy the driver + installer into the fake repo (so paths resolve).
cp "$DRIVER_SCRIPT" "$FAKE/scripts/git/"
cp "$INSTALLER" "$FAKE/scripts/setup/"

# .gitattributes wires the driver to .chump/state.sql.
cat >"$FAKE/.gitattributes" <<'GA'
.chump/state.sql merge=chump-state-sql-regen
GA

# Stub `chump` binary that writes a deterministic "regenerated" output.
# The driver shells out to `$CHUMP_BIN gap dump --out <path>`; the stub
# just writes a marker we can verify in the result.
STUB_CHUMP="$TMPDIR_BASE/chump-stub"
cat >"$STUB_CHUMP" <<'STUB'
#!/usr/bin/env bash
# chump stub: only handles `gap dump --out <path>`
if [[ "$1" == "gap" && "$2" == "dump" && "$3" == "--out" ]]; then
    cat >"$4" <<'DUMP'
-- regenerated dump (test fixture)
INSERT INTO gaps VALUES ('CANONICAL-FROM-DB', 'open');
DUMP
    exit 0
fi
echo "stub chump: unsupported args: $*" >&2
exit 99
STUB
chmod +x "$STUB_CHUMP"

# Stub the .chump/state.db file so the driver's "db must exist" check passes.
touch "$FAKE/.chump/state.db"

# Seed a base commit on main with .chump/state.sql at v1.
mkdir -p "$FAKE/.chump"
echo "-- v1 dump (ancestor)" > "$FAKE/.chump/state.sql"
git -C "$FAKE" add .gitattributes scripts/ .chump/state.sql
git -C "$FAKE" commit -q -m "seed: state.sql v1"

# Install drivers in this fake repo's .git/config.
( cd "$FAKE" && bash scripts/setup/install-merge-drivers.sh ) >/dev/null 2>&1

# ── Test 1: drivers were registered ────────────────────────────────────────
echo "--- Test 1: install-merge-drivers.sh registered the chump-state-sql-regen driver ---"
if git -C "$FAKE" config --get merge.chump-state-sql-regen.driver >/dev/null; then
    ok "merge.chump-state-sql-regen.driver registered"
else
    fail "driver NOT registered in .git/config"
fi

# ── Test 2: rebase across diverging state.sql edits resolves cleanly ──────
echo "--- Test 2: simulated multi-agent rebase on .chump/state.sql ---"

# Branch A modifies state.sql.
git -C "$FAKE" checkout -q -b feature-A
echo "-- v2-A dump (feature A)" > "$FAKE/.chump/state.sql"
git -C "$FAKE" add .chump/state.sql
git -C "$FAKE" commit -q -m "feature-A: state.sql v2-A"

# Branch B (off main) makes a different mod and lands on main.
git -C "$FAKE" checkout -q main
git -C "$FAKE" checkout -q -b feature-B
echo "-- v2-B dump (feature B - landed on main)" > "$FAKE/.chump/state.sql"
git -C "$FAKE" add .chump/state.sql
git -C "$FAKE" commit -q -m "feature-B: state.sql v2-B"
git -C "$FAKE" checkout -q main
git -C "$FAKE" merge -q --ff-only feature-B
git -C "$FAKE" branch -q -D feature-B

# Now feature-A rebases onto main — expected: no conflict markers, state.sql
# regenerated to canonical "DUMP" content from our stub.
git -C "$FAKE" checkout -q feature-A
set +e
( cd "$FAKE" && CHUMP_BIN="$STUB_CHUMP" git rebase main 2>&1 ) > "$TMPDIR_BASE/rebase.out"
RC=$?
set -e

if [[ $RC -ne 0 ]]; then
    fail "rebase exited rc=$RC; output:"
    sed 's/^/      /' < "$TMPDIR_BASE/rebase.out"
elif grep -q "<<<<<<< " "$FAKE/.chump/state.sql"; then
    fail "state.sql still has conflict markers after rebase"
elif grep -q "CANONICAL-FROM-DB" "$FAKE/.chump/state.sql"; then
    ok "rebase succeeded; state.sql regenerated by driver (canonical content present)"
else
    fail "rebase succeeded but state.sql content unexpected:"
    sed 's/^/      /' < "$FAKE/.chump/state.sql"
fi

# ── Test 3: driver no-ops gracefully when chump is missing ────────────────
echo "--- Test 3: driver gracefully falls back to manual conflict when chump missing ---"
git -C "$FAKE" checkout -q main
git -C "$FAKE" checkout -q -b feature-C
echo "-- v3-C dump" > "$FAKE/.chump/state.sql"
git -C "$FAKE" add .chump/state.sql
git -C "$FAKE" commit -q -m "feature-C: state.sql v3-C"
git -C "$FAKE" checkout -q main
git -C "$FAKE" checkout -q -b feature-D
echo "-- v3-D dump" > "$FAKE/.chump/state.sql"
git -C "$FAKE" add .chump/state.sql
git -C "$FAKE" commit -q -m "feature-D: state.sql v3-D"
git -C "$FAKE" checkout -q main
git -C "$FAKE" merge -q --ff-only feature-D
git -C "$FAKE" checkout -q feature-C

# Run rebase with CHUMP_BIN pointing at /dev/null/no-such-bin — driver should
# exit 1, git falls back to default merge (conflict markers), rebase pauses.
set +e
( cd "$FAKE" && CHUMP_BIN=/no/such/chump-bin git rebase main 2>&1 ) > "$TMPDIR_BASE/rebase-fallback.out"
RC=$?
set -e

# We expect non-zero rc (rebase paused with conflict).
if [[ $RC -eq 0 ]]; then
    fail "rebase succeeded silently when driver should have failed (no chump binary)"
elif grep -q "<<<<<<< " "$FAKE/.chump/state.sql"; then
    ok "graceful fallback: rebase paused with conflict markers when chump unavailable"
else
    # Some git versions still try the driver and just exit cleanly without writing markers.
    # Either way the test passes if the rebase didn't silently bork.
    ok "rebase exited rc=$RC without silent corruption (no-chump fallback path)"
fi
git -C "$FAKE" rebase --abort 2>/dev/null || true

echo
echo "=== Results: $PASS passed, $FAIL failed ==="
[ "$FAIL" -eq 0 ]
