#!/usr/bin/env bash
# test-pr-watch-auto-resolve.sh — INFRA-387 unit test for the
# attempt_auto_resolve_conflicts helper added to pr-watch.sh.
#
# Tests the recipe in isolation (sources the helper from pr-watch.sh
# instead of standing up a full PR-with-conflicts scenario, which
# requires a remote + auto-merge state). 5 cases:
#
#   1. .chump/state.sql conflict → regenerated via mocked chump
#   2. docs/gaps/<ID>.yaml conflict → take ours, git add
#   3. .github/workflows/ci.yml conflict → conflict markers stripped
#   4. mixed conflicts (state.sql + gaps yaml) → both auto-resolve
#   5. unrecognized conflict (e.g. src/foo.rs) → return 1, leave for operator
#   6. CHUMP_AUTO_RESOLVE_CONFLICTS=0 → return 1, no work done

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
PR_WATCH="$REPO_ROOT/scripts/coord/pr-watch.sh"

[[ -f "$PR_WATCH" ]] || { echo "[FAIL] pr-watch.sh not found"; exit 1; }

TMP="$(cd "$(mktemp -d)" && pwd -P)"
trap 'rm -rf "$TMP"' EXIT

# Mock chump on PATH — `chump gap dump --out FILE` writes a sentinel.
mkdir -p "$TMP/bin"
cat > "$TMP/bin/chump" <<'STUB'
#!/usr/bin/env bash
# Mock: handle `chump gap dump --out <path>` by writing a sentinel.
# Use positional args ($1..$4) instead of "${*##* }" — the latter
# returned the full string unchanged on the test bash, leaving the
# sentinel written to a file literally named "gap dump --out X".
if [[ "$1 $2 $3" == "gap dump --out" && -n "$4" ]]; then
    printf -- "-- regenerated by mock chump --\n" > "$4"
fi
exit 0
STUB
chmod +x "$TMP/bin/chump"

# Source the helper from pr-watch.sh. We need `say` defined first
# (the helper calls it) and PR + BRANCH set (used by `say`).
PR=999
BRANCH=test-branch
say() { echo "[say] $*"; }

# Extract just the helper function via a sed range. It's bounded by
# the 'attempt_auto_resolve_conflicts() {' opening and the matching '}'.
helper_src=$(awk '/^attempt_auto_resolve_conflicts\(\) \{/{p=1} p{print} /^\}/ && p{exit}' "$PR_WATCH")
[[ -z "$helper_src" ]] && { echo "[FAIL] couldn't extract helper from $PR_WATCH"; exit 1; }
eval "$helper_src"

# Bash assignment-prefix `VAR=val cmd` doesn't propagate VAR into a
# shell function call (only to executable commands). Export PATH so
# the chump mock is found by the function's subprocesses.
export PATH="$TMP/bin:$PATH"

# Run a synthetic conflict in a fresh git repo. Each case sets up unmerged
# files via `git update-index --unmerged` directly so we don't have to
# orchestrate a real rebase.
setup_repo() {
    local d="$1"
    rm -rf "$d" && mkdir -p "$d"
    cd "$d"
    git init -q -b main
    git config user.email t@t && git config user.name t
    mkdir -p .chump docs/gaps .github/workflows
    touch a.txt && git add a.txt && git commit -qm "init"
}

# Add a file as unmerged (stages 1+2+3, no stage 0). Easiest: write the
# content with conflict markers + use git update-index to mark stages.
make_unmerged() {
    local f="$1" content="$2"
    mkdir -p "$(dirname "$f")"
    printf '%s' "$content" > "$f"
    # Stage as unmerged: write content to all three stages so it shows
    # up in `git diff --diff-filter=U`.
    local hash
    hash=$(git hash-object -w "$f")
    printf '%o %s 1\t%s\n%o %s 2\t%s\n%o %s 3\t%s\n' \
        100644 "$hash" "$f" \
        100644 "$hash" "$f" \
        100644 "$hash" "$f" \
        | git update-index --index-info
}

# ── Test 1: state.sql conflict ───────────────────────────────────────────
echo "Test 1: .chump/state.sql conflict → regenerated via chump"
setup_repo "$TMP/r1"
make_unmerged ".chump/state.sql" "old
new
"
PATH="$TMP/bin:$PATH" attempt_auto_resolve_conflicts  # NOTE: see export below
rc=$?
[[ $rc -eq 0 ]] || { echo "[FAIL] expected rc=0 got $rc"; exit 1; }
grep -q "regenerated by mock chump" .chump/state.sql || { echo "[FAIL] state.sql not regenerated"; exit 1; }
[[ -z "$(git diff --name-only --diff-filter=U)" ]] || { echo "[FAIL] file still unmerged"; exit 1; }
echo "[PASS]"

# ── Test 2: docs/gaps/INFRA-NNN.yaml conflict ────────────────────────────
# why this is OK: INFRA-100 and INFRA-200 below are synthetic fixture IDs
# created inside $TMP/r2 / $TMP/r4 (isolated mktemp git repos). They do not
# reference real gap files from the live repo — the contract under test is the
# auto-resolve conflict strategy for the docs/gaps/*.yaml path pattern.
echo ""
echo "Test 2: docs/gaps/INFRA-100.yaml → take ours"
setup_repo "$TMP/r2"
make_unmerged "docs/gaps/INFRA-100.yaml" "id: INFRA-100
status: open
"
PATH="$TMP/bin:$PATH" attempt_auto_resolve_conflicts  # NOTE: see export below
rc=$?
[[ $rc -eq 0 ]] || { echo "[FAIL] expected rc=0 got $rc"; exit 1; }
[[ -z "$(git diff --name-only --diff-filter=U)" ]] || { echo "[FAIL] file still unmerged"; exit 1; }
echo "[PASS]"

# ── Test 3: ci.yml conflict markers stripped ─────────────────────────────
echo ""
echo "Test 3: ci.yml → strip conflict markers"
setup_repo "$TMP/r3"
make_unmerged ".github/workflows/ci.yml" "name: CI
some_field: foo
some_field: bar
end:
"
PATH="$TMP/bin:$PATH" attempt_auto_resolve_conflicts  # NOTE: see export below
rc=$?
[[ $rc -eq 0 ]] || { echo "[FAIL] expected rc=0 got $rc"; exit 1; }
if grep -qE '^(<<<<<<< |=======$|>>>>>>> )' .github/workflows/ci.yml; then
    echo "[FAIL] markers still present"
    cat .github/workflows/ci.yml
    exit 1
fi
echo "[PASS]"

# ── Test 4: mixed (state.sql + gaps yaml) ────────────────────────────────
# why this is OK: INFRA-200 is a synthetic fixture ID created inside $TMP/r4
# (an isolated mktemp git repo). No real docs/gaps/INFRA-200.yaml is read.
echo ""
echo "Test 4: mixed state.sql + docs/gaps/*.yaml conflicts"
setup_repo "$TMP/r4"
make_unmerged ".chump/state.sql" "stale"
make_unmerged "docs/gaps/INFRA-200.yaml" "stale"
PATH="$TMP/bin:$PATH" attempt_auto_resolve_conflicts  # NOTE: see export below
rc=$?
[[ $rc -eq 0 ]] || { echo "[FAIL] expected rc=0 got $rc"; exit 1; }
[[ -z "$(git diff --name-only --diff-filter=U)" ]] || { echo "[FAIL] files still unmerged"; exit 1; }
echo "[PASS]"

# ── Test 5: unrecognized file → bail ─────────────────────────────────────
echo ""
echo "Test 5: src/foo.rs conflict → bail (return 1)"
setup_repo "$TMP/r5"
make_unmerged "src/foo.rs" "fn main() {}"
set +e
PATH="$TMP/bin:$PATH" attempt_auto_resolve_conflicts  # NOTE: see export below
rc=$?
set -e
[[ $rc -ne 0 ]] || { echo "[FAIL] expected rc!=0 (bail) got $rc"; exit 1; }
# File should still be unmerged — operator needs to resolve
[[ -n "$(git diff --name-only --diff-filter=U)" ]] || { echo "[FAIL] file should remain unmerged"; exit 1; }
echo "[PASS]"

# ── Test 6: bypass env ───────────────────────────────────────────────────
echo ""
echo "Test 6: CHUMP_AUTO_RESOLVE_CONFLICTS=0 → bypass (return 1, no work)"
setup_repo "$TMP/r6"
make_unmerged ".chump/state.sql" "stale"
set +e
PATH="$TMP/bin:$PATH" CHUMP_AUTO_RESOLVE_CONFLICTS=0 attempt_auto_resolve_conflicts
rc=$?
set -e
[[ $rc -ne 0 ]] || { echo "[FAIL] expected rc!=0 (bypass), got $rc"; exit 1; }
# state.sql should still have the stale content + still be unmerged
[[ "$(cat .chump/state.sql)" == "stale" ]] || { echo "[FAIL] bypass should not modify file"; exit 1; }
echo "[PASS]"

echo ""
echo "[OK] all 6 INFRA-387 auto-resolve cases passed"
