#!/usr/bin/env bash
# test-pre-commit-claim-contract.sh — CI tests for RESILIENT-026 claim contract.
#
# Tests 6 fixtures:
#   1. paths-in-claim PASS
#   2. paths-out-of-claim FAIL
#   3. autogenerated-file-allowed PASS (.chump/state.sql, docs/gaps/, .gitignore)
#   4. branch-matches PASS  (pre-push guard)
#   5. branch-mismatch FAIL  (pre-push guard)
#   6. bypass-overrides-all PASS (Off-Rails-Bypass trailer bypasses both guards)
#
# References: RESILIENT-025 (subject guard), RESILIENT-026 (paths+branch guard)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PRE_COMMIT_HOOK="$REPO_ROOT/scripts/git-hooks/pre-commit"
PRE_PUSH_HOOK="$REPO_ROOT/scripts/git-hooks/pre-push"

PASS=0
FAIL=0
ERRORS=""

pass() { echo "PASS: $1"; PASS=$((PASS + 1)); }
fail() { echo "FAIL: $1"; FAIL=$((FAIL + 1)); ERRORS="${ERRORS}  - $1\n"; }

# ---------------------------------------------------------------------------
# Fixture helpers
# ---------------------------------------------------------------------------

# Create a minimal git repo with a real initial commit.
setup_git_repo() {
    local dir="$1"
    git init -q "$dir"
    git -C "$dir" config user.email "agent@chump.local"
    git -C "$dir" config user.name "TestAgent"
    echo "root" > "$dir/README.md"
    git -C "$dir" add README.md
    git -C "$dir" commit -q -m "chore: root"
}

# Write a claim-*.json with the given gap_id and paths.
make_claim_file() {
    local locks_dir="$1" gap_id="$2"; shift 2
    mkdir -p "$locks_dir"
    local expires
    expires="$(date -u -v+1H +%Y-%m-%dT%H:%M:%SZ 2>/dev/null \
               || date -u -d '+1 hour' +%Y-%m-%dT%H:%M:%SZ 2>/dev/null \
               || echo '2099-01-01T00:00:00Z')"
    local paths_json="[]"
    if [ "$#" -gt 0 ]; then
        paths_json="[$(printf '"%s",' "$@" | sed 's/,$//')]"
    fi
    cat > "$locks_dir/claim-${gap_id}-test.json" <<JSON
{
  "gap_id": "${gap_id}",
  "session_id": "test-session-resilient-026",
  "expires_at": "${expires}",
  "paths": ${paths_json}
}
JSON
}

# Run the pre-commit hook in a fixture repo with a git shim that controls
# which files appear as "staged" and a synthetic COMMIT_EDITMSG.
#
# The hook MUST run with cwd = fixture_dir so that `git rev-parse --git-dir`
# returns ".git" (relative) which the hook then resolves as
# ".git/COMMIT_EDITMSG" correctly.
#
# Args: fixture_dir staged_files_newline_sep commit_msg
# Returns: hook stdout+stderr; exit code reflects hook exit.
run_pre_commit() {
    local fixture_dir="$1" staged_files="$2" commit_msg="$3"

    # Write COMMIT_EDITMSG using the absolute git-dir path (safe from any cwd).
    local abs_git_dir
    abs_git_dir="$(git -C "$fixture_dir" rev-parse --absolute-git-dir 2>/dev/null)"
    printf '%s\n' "$commit_msg" > "${abs_git_dir}/COMMIT_EDITMSG"

    # Build a git shim that intercepts `diff --cached --name-only`.
    local shim_dir="$fixture_dir/_shims"
    mkdir -p "$shim_dir"
    # Write staged-files list to a temp file the shim can cat.
    printf '%s\n' "$staged_files" > "$fixture_dir/_staged_files"
    # The shim: intercept --name-only, else delegate to real git.
    # We find real git by removing shim_dir from PATH before calling command -v.
    local real_git
    real_git="$(command -v git)"
    cat > "$shim_dir/git" <<SHIMEOF
#!/usr/bin/env bash
for _a in "\$@"; do
    if [[ "\$_a" == "--name-only" ]]; then
        cat "${fixture_dir}/_staged_files" 2>/dev/null || true
        exit 0
    fi
done
exec "${real_git}" "\$@"
SHIMEOF
    chmod +x "$shim_dir/git"

    # Run the hook with cwd=fixture_dir and all unrelated guards disabled.
    (
        cd "$fixture_dir"
        CHUMP_OFF_RAILS_CHECK=1 \
        CHUMP_LEASE_CHECK=0 \
        CHUMP_STOMP_WARN=0 \
        CHUMP_GAPS_LOCK=0 \
        CHUMP_SUBMODULE_CHECK=0 \
        CHUMP_BOOK_SYNC_CHECK=0 \
        CHUMP_CREDENTIAL_CHECK=0 \
        CHUMP_DOCS_DELTA_CHECK=0 \
        CREDIBLE_INFRA_SMOKE_BYPASS=1 \
        CHUMP_EVENT_REGISTRY_CHECK=0 \
        CHUMP_EFFECT_METRIC_CHECK=0 \
        CHUMP_OBS_BUDGET_BYPASS=1 \
        CHUMP_DEFAULT_FLIP_CHECK=0 \
        CHUMP_GAP_DIVERGE_CHECK=0 \
        CHUMP_GIT_IDENTITY_CHECK=0 \
        CHUMP_HARDCODED_DATE_CHECK=0 \
        CHUMP_RUST_FIRST_CHECK=0 \
        CHUMP_REDUNDANCY_CHECK=0 \
        CHUMP_AC_COMPLETENESS_CHECK=0 \
        CHUMP_MAIN_WT_CONFIG_CHECK=0 \
        CHUMP_PWA_INDEX_UNIQ_CHECK=0 \
        CHUMP_BRANCH_PROTECTION_AUDIT=0 \
        CHUMP_AC_CHECK=0 \
        CHUMP_TEST_LAG_CHECK=0 \
        CHUMP_DEVIATION_DOC_CHECK=0 \
        CHUMP_SCOPE_CHECK=0 \
        CHUMP_PREREG_CHECK=0 \
        CHUMP_CHECK_BUILD=0 \
        PATH="$shim_dir:$PATH" \
            bash --noprofile --norc "$PRE_COMMIT_HOOK" 2>&1 || true
    )
}

# Run just the Guard 5 block from pre-push in a fixture repo.
# Args: fixture_dir (must have a real HEAD commit)
run_pre_push_branch_check() {
    local fixture_dir="$1"

    CHUMP_OFF_RAILS_CHECK=1 \
    REPO_ROOT="$fixture_dir" \
        bash -c "
            set -euo pipefail
            REPO_ROOT='$fixture_dir'
            # Source only the Guard 5 block
$(sed -n '/^# Guard 5: Branch-name/,/^fi$/p' "$PRE_PUSH_HOOK")
            exit 0
        " 2>&1 || true
}

# ---------------------------------------------------------------------------
# Test 1: paths-in-claim PASS
# All staged files are in claim.paths → should NOT block
# ---------------------------------------------------------------------------
T1="$(mktemp -d)" && trap 'rm -rf "$T1"' EXIT
setup_git_repo "$T1"
make_claim_file "$T1/.chump-locks" "RESILIENT-026" \
    "scripts/git-hooks/pre-commit" "scripts/git-hooks/pre-push"
out1=$(run_pre_commit "$T1" \
    "$(printf 'scripts/git-hooks/pre-commit\nscripts/git-hooks/pre-push')" \
    "fix(RESILIENT-026): extend claim contract")
if echo "$out1" | grep -q "BLOCKED (RESILIENT-026)"; then
    fail "Test 1: paths-in-claim should PASS — got BLOCKED: $out1"
else
    pass "Test 1: paths-in-claim PASS"
fi

# ---------------------------------------------------------------------------
# Test 2: paths-out-of-claim FAIL
# Staged file NOT in claim.paths → should block
# ---------------------------------------------------------------------------
T2="$(mktemp -d)" && trap 'rm -rf "$T2"' EXIT
setup_git_repo "$T2"
make_claim_file "$T2/.chump-locks" "RESILIENT-026" \
    "scripts/git-hooks/pre-commit"
out2=$(run_pre_commit "$T2" \
    "$(printf 'scripts/git-hooks/pre-commit\nsrc/main.rs')" \
    "fix(RESILIENT-026): extend claim contract")
if echo "$out2" | grep -q "BLOCKED (RESILIENT-026)"; then
    pass "Test 2: paths-out-of-claim FAIL (blocked as expected)"
else
    fail "Test 2: paths-out-of-claim should be BLOCKED — got: $out2"
fi

# ---------------------------------------------------------------------------
# Test 3: autogenerated-file-allowed PASS
# .chump/state.sql, docs/gaps/*.yaml, .gitignore always allowed regardless
# of claim.paths
# ---------------------------------------------------------------------------
T3="$(mktemp -d)" && trap 'rm -rf "$T3"' EXIT
setup_git_repo "$T3"
# Claim is narrow — only the hook file
make_claim_file "$T3/.chump-locks" "RESILIENT-026" \
    "scripts/git-hooks/pre-commit"
out3=$(run_pre_commit "$T3" \
    "$(printf 'scripts/git-hooks/pre-commit\n.chump/state.sql\ndocs/gaps/RESILIENT-026.yaml\n.gitignore')" \
    "fix(RESILIENT-026): extend claim contract")
if echo "$out3" | grep -q "BLOCKED (RESILIENT-026)"; then
    fail "Test 3: autogenerated-file-allowed should PASS — got BLOCKED: $out3"
else
    pass "Test 3: autogenerated-file-allowed PASS (.chump/state.sql, docs/gaps/*.yaml, .gitignore)"
fi

# ---------------------------------------------------------------------------
# Test 4: branch-matches PASS (pre-push guard)
# Branch = chump/resilient-026-claim → should not block
# ---------------------------------------------------------------------------
T4="$(mktemp -d)" && trap 'rm -rf "$T4"' EXIT
setup_git_repo "$T4"
git -C "$T4" checkout -q -b "chump/resilient-026-claim"
make_claim_file "$T4/.chump-locks" "RESILIENT-026"
# Add a real commit (Guard 5 reads HEAD commit for bypass trailer)
echo "impl" > "$T4/impl.txt"
git -C "$T4" add impl.txt
git -C "$T4" commit -q -m "fix(RESILIENT-026): branch matches"

out4=$(run_pre_push_branch_check "$T4")
if echo "$out4" | grep -q "BLOCKED (RESILIENT-026)"; then
    fail "Test 4: branch-matches should PASS — got BLOCKED: $out4"
else
    pass "Test 4: branch-matches PASS"
fi

# ---------------------------------------------------------------------------
# Test 5: branch-mismatch FAIL (pre-push guard)
# Branch ≠ expected and no bypass trailer → should block
# ---------------------------------------------------------------------------
T5="$(mktemp -d)" && trap 'rm -rf "$T5"' EXIT
setup_git_repo "$T5"
git -C "$T5" checkout -q -b "chump/resilient-026-wrong"
make_claim_file "$T5/.chump-locks" "RESILIENT-026"
echo "impl" > "$T5/impl.txt"
git -C "$T5" add impl.txt
git -C "$T5" commit -q -m "fix(RESILIENT-026): wrong branch"

out5=$(run_pre_push_branch_check "$T5")
if echo "$out5" | grep -q "BLOCKED (RESILIENT-026)"; then
    pass "Test 5: branch-mismatch FAIL (blocked as expected)"
else
    fail "Test 5: branch-mismatch should be BLOCKED — got: $out5"
fi

# ---------------------------------------------------------------------------
# Test 6: bypass-overrides-all PASS
# Off-Rails-Bypass trailer bypasses both the pre-commit paths check AND
# the pre-push branch-name check
# ---------------------------------------------------------------------------
T6="$(mktemp -d)" && trap 'rm -rf "$T6"' EXIT
setup_git_repo "$T6"
# Wrong branch + out-of-claim paths — both should be bypassed
git -C "$T6" checkout -q -b "chump/resilient-026-wrong-branch"
make_claim_file "$T6/.chump-locks" "RESILIENT-026" \
    "scripts/git-hooks/pre-commit"
echo "impl" > "$T6/impl.txt"
git -C "$T6" add impl.txt
git -C "$T6" commit -q -m "$(printf 'fix(RESILIENT-026): bypass test\n\nOff-Rails-Bypass: testing bypass path in CI fixture')"

# Test 6a: pre-commit paths bypass
out6a=$(run_pre_commit "$T6" \
    "$(printf 'src/main.rs')" \
    "$(printf 'fix(RESILIENT-026): bypass test\n\nOff-Rails-Bypass: testing bypass path in CI fixture')")

# Test 6b: pre-push branch bypass
out6b=$(run_pre_push_branch_check "$T6")

commit_blocked=0
push_blocked=0
echo "$out6a" | grep -q "BLOCKED (RESILIENT-026)" && commit_blocked=1 || true
echo "$out6b" | grep -q "BLOCKED (RESILIENT-026)" && push_blocked=1 || true

if [ "$commit_blocked" = "0" ] && [ "$push_blocked" = "0" ]; then
    pass "Test 6: bypass-overrides-all PASS (Off-Rails-Bypass bypasses paths+branch guards)"
else
    fail "Test 6: bypass should override all — commit_blocked=$commit_blocked push_blocked=$push_blocked; pre-commit: $out6a; pre-push: $out6b"
fi

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo "Results: $PASS passed, $FAIL failed"
if [ "$FAIL" -gt 0 ]; then
    printf "Failures:\n%b" "$ERRORS"
    exit 1
fi
exit 0
