#!/usr/bin/env bash
# install-sccache.sh — INFRA-202: shared compilation cache for fleet worktrees.
#
# Each linked worktree under .claude/worktrees/ has its own target/ dir.
# Without a shared compilation cache, every fresh worktree pays a 5-15 min
# cold-build cost when bot-merge.sh runs cargo check / clippy / test. With
# sccache as a rustc wrapper, the rustc invocations are cached at the
# crate-compilation level — second worktree to build a given crate version
# gets it from cache in seconds.
#
# Concrete impact (observed 2026-05-01): bot-merge.sh hit a 900s clippy
# timeout because the worktree was on a fresh cargo cache. With sccache,
# that drops to <60s for a no-source-change rebuild.
#
# What this script does:
#   1. brew install sccache (idempotent — skips if already installed)
#   2. Write .cargo/config.toml with rustc-wrapper=sccache + cache dir
#   3. Verify with `cargo check --bin chump` and report cache hit rate
#
# Run this once per machine. .cargo/config.toml is .gitignored so each
# machine controls its own cache config — feel free to tune the cache size
# or disable by removing the file.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

echo "[install-sccache] checking for sccache …"
if ! command -v sccache >/dev/null 2>&1; then
    echo "[install-sccache] sccache not found — installing via brew"
    if ! command -v brew >/dev/null 2>&1; then
        echo "[install-sccache] ERROR: brew not found. Install Homebrew first or"
        echo "[install-sccache] install sccache another way (cargo install sccache)."
        exit 1
    fi
    brew install sccache
else
    echo "[install-sccache] sccache already installed ($(sccache --version | head -1))"
fi

echo "[install-sccache] writing .cargo/config.toml"
mkdir -p .cargo
cat > .cargo/config.toml <<'EOF'
# INFRA-202: sccache as rustc wrapper for fleet worktrees.
# Generated by scripts/setup/install-sccache.sh — do not edit by hand,
# re-run the script if you need to regenerate.
#
# .gitignore'd because per-machine: a CI runner without sccache would
# break here.
[build]
rustc-wrapper = "sccache"

[env]
# 10 GB cache, large enough for chump's full dep tree several times over.
SCCACHE_CACHE_SIZE = "10G"
# Local disk cache (default ~/.cache/sccache). Override with
# SCCACHE_DIR=/path if you want to put it on faster storage.
EOF

echo "[install-sccache] verifying with cargo check …"
sccache --zero-stats >/dev/null 2>&1 || true
if cargo check --bin chump >/tmp/install-sccache-check.log 2>&1; then
    echo "[install-sccache] cargo check OK"
    echo "[install-sccache] sccache stats:"
    sccache --show-stats | grep -E "compile requests|cache hits|cache misses" | sed 's/^/  /'
else
    echo "[install-sccache] WARN: cargo check failed; see /tmp/install-sccache-check.log"
    echo "[install-sccache] config is in place but verification did not complete"
    exit 1
fi

echo "[install-sccache] done. Future cargo invocations in any worktree will use sccache."
echo "[install-sccache] To opt out on this machine: rm .cargo/config.toml"
