#!/usr/bin/env bash
# bot-shipped-audit.sh — daily report on autonomous bot-shipped PRs.
# Surfaces things you'd want to spot-check WITHOUT reviewing each PR.
#
# Outputs to stdout (or --output FILE). Designed for cron + email/discord.
#
# Usage:
#   scripts/bot-shipped-audit.sh                       # last 24h
#   scripts/bot-shipped-audit.sh --since 2026-04-19    # specific date
#   scripts/bot-shipped-audit.sh --since 2026-04-19 --output /tmp/audit.md

set -u

SINCE="${1:-}"
if [ "$SINCE" = "--since" ]; then
  SINCE="$2"
elif [ -z "$SINCE" ]; then
  # Default: last 24h
  if date -v-1d +%Y-%m-%d >/dev/null 2>&1; then
    SINCE=$(date -v-1d +%Y-%m-%d)  # macOS
  else
    SINCE=$(date -d "1 day ago" +%Y-%m-%d)  # GNU
  fi
fi

OUTPUT="${OUTPUT:-/dev/stdout}"

echo "# Bot-shipped PR audit — since $SINCE"
echo ""
echo "Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo ""

# 1. PRs merged since SINCE
echo "## 1. PRs merged since $SINCE"
echo ""
PRS=$(gh pr list --state merged --search "is:pr is:merged created:>=$SINCE" --limit 50 --json number,title,additions,deletions,files --jq '.[] | "\(.number)|\(.title)|\(.additions)|\(.deletions)|\(.files | length)"')
echo "$PRS" | awk -F'|' 'BEGIN { print "| PR | + | - | files | title |"; print "|---|---|---|---|---|" } { printf "| #%s | +%s | -%s | %s | %s |\n", $1, $3, $4, $5, substr($2,1,55) }'

PR_COUNT=$(echo "$PRS" | grep -c .)
echo ""
echo "**Total: $PR_COUNT PRs merged**"
echo ""

# 2. Quality flags — things that warrant a spot-check
echo "## 2. Quality flags (spot-check candidates)"
echo ""

# 2a. Large PRs (>500 LOC added)
echo "### Large PRs (>500 LOC added — review for scope creep)"
echo ""
LARGE=$(echo "$PRS" | awk -F'|' '$3 > 500 { printf "- PR #%s (+%s LOC) — %s\n", $1, $3, substr($2,1,60) }')
[ -n "$LARGE" ] && echo "$LARGE" || echo "None."
echo ""

# 2b. PRs touching many files (>10)
echo "### Multi-file PRs (>10 files — review for atomic-PR discipline)"
echo ""
MULTI=$(echo "$PRS" | awk -F'|' '$5 > 10 { printf "- PR #%s (%s files) — %s\n", $1, $5, substr($2,1,60) }')
[ -n "$MULTI" ] && echo "$MULTI" || echo "None."
echo ""

# 2c. PRs touching production src/ paths (vs docs/)
echo "### Production src/ changes (review for test coverage)"
echo ""
SRC_PRS=()
for pr_num in $(echo "$PRS" | cut -d'|' -f1); do
  has_src=$(gh pr view "$pr_num" --json files --jq '.files[].path | select(startswith("src/") or startswith("crates/") and contains("/src/"))' 2>/dev/null | head -1)
  if [ -n "$has_src" ]; then
    title=$(echo "$PRS" | grep "^$pr_num|" | cut -d'|' -f2)
    echo "- PR #$pr_num — ${title:0:60}"
  fi
done
echo ""

# 3. CI failures or admin merges
echo "## 3. Admin merges / CI bypasses"
echo ""
echo "(Spot-checked: PRs that merged with CI not green or via --admin override.)"
ADMIN=$(gh pr list --state merged --search "is:pr is:merged created:>=$SINCE" --json number,title,mergedBy,mergeCommit --jq '.[] | select(.mergedBy.login == "repairman29") | "\(.number)|\(.title[:50])"' 2>/dev/null)
echo "$ADMIN" | awk -F'|' '{ printf "- PR #%s — %s\n", $1, $2 }' | head -10
echo ""

# 4. Reflection summary (orchestrator dispatched work)
echo "## 4. Orchestrator dispatch outcomes"
echo ""
if [ -f sessions/chump_memory.db ]; then
  sqlite3 sessions/chump_memory.db "SELECT scope, count(*) FROM chump_improvement_targets WHERE scope LIKE 'dispatch:%' GROUP BY scope" 2>/dev/null | awk -F'|' '{ printf "- %s: %s outcomes\n", $1, $2 }'
else
  echo "(no chump_memory.db yet — orchestrator hasn't logged any dispatches)"
fi
echo ""

# 5. Outstanding open PRs (anything stuck)
echo "## 5. Open PRs (anything stuck waiting on you)"
echo ""
gh pr list --state open --json number,title,mergeStateStatus,createdAt --jq '.[] | "- PR #\(.number) [\(.mergeStateStatus)] — \(.title[:55]) (created \(.createdAt[:10]))"'
echo ""

echo "---"
echo "_Audit generated by scripts/bot-shipped-audit.sh — install via launchd for daily delivery._"
