#!/usr/bin/env python3
"""doctrine-publish.py — META-1044 (META-256 Doctrine Loom auto-publish).

Regenerates, from the seam-finder graph:
  <out-dir>/DOCTRINE_INDEX.md  — canonical entry point: every playbook with
                                  topics, inbound-reference count, last-modified.
  <out-dir>/DOCTRINE_GRAPH.md  — Mermaid diagram of the cross-reference graph.

Output is deterministic for a given tree (dates come from file mtimes), and
files are only rewritten when their content changed. Prints the names of the
files it (re)wrote, one per line.

Usage: doctrine-publish.py [--root DIR] [--out-dir DIR]
"""
import argparse
import datetime
import importlib.util
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
_spec = importlib.util.spec_from_file_location(
    "doctrine_seam_finder", os.path.join(HERE, "doctrine-seam-finder.py"))
seam = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(seam)

BANNER = ("<!-- AUTO-GENERATED by scripts/coord/doctrine-publish.py "
          "(META-1044 / Doctrine Loom). Do not edit by hand. -->\n")


def node_id(path):
    return "n" + "".join(c if c.isalnum() else "_" for c in path)


def mtime(root, rel):
    ts = os.path.getmtime(os.path.join(root, rel))
    return datetime.datetime.fromtimestamp(ts, datetime.timezone.utc).strftime("%Y-%m-%d")


def render_index(root, graph):
    lines = [BANNER, "# Doctrine Index\n",
             "Canonical entry point to the playbook set, regenerated by the Doctrine "
             "Loom. Governing primitives (this index references itself):\n",
             "- `scripts/coord/doctrine-loom-daemon.sh` — the scheduled Loom",
             "- `scripts/coord/doctrine-seam-finder.py` — reference graph + topic overlap",
             "- `scripts/coord/doctrine-weave-detectors.py` — missing-thread / frayed-edge detectors",
             "- [DOCTRINE_INDEX.md](DOCTRINE_INDEX.md) — this file; "
             "[DOCTRINE_GRAPH.md](DOCTRINE_GRAPH.md) — the graph view\n",
             f"{len(graph['playbooks'])} playbooks.\n",
             "| Playbook | Title | Topics | Inbound refs | Last modified |",
             "|---|---|---|---|---|"]
    for p in sorted(graph["playbooks"], key=lambda p: p["path"]):
        topics = ", ".join(p["topics"][:6])
        title = p["title"].replace("|", "\\|")
        lines.append(f"| `{p['path']}` | {title} | {topics} | {p['inbound_count']} | "
                     f"{mtime(root, p['path'])} |")
    return "\n".join(lines) + "\n"


def render_graph(graph):
    lines = [BANNER, "# Doctrine Graph\n",
             "Playbook cross-references (arrow = \"references\"; dashed = one-way, "
             "i.e. the target does not reference back).\n",
             "```mermaid", "graph LR"]
    for p in graph["playbooks"]:
        label = os.path.basename(p["path"]).replace('"', "'")
        lines.append(f'    {node_id(p["path"])}["{label}"]')
    for e in graph["edges"]:
        arrow = "-.->" if e["asymmetric"] else "-->"
        lines.append(f"    {node_id(e['from'])} {arrow} {node_id(e['to'])}")
    lines.append("```")
    return "\n".join(lines) + "\n"


def write_if_changed(path, content):
    try:
        with open(path, encoding="utf-8") as fh:
            if fh.read() == content:
                return False
    except OSError:
        pass
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
    return True


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--root", default=os.path.join(HERE, "..", ".."))
    ap.add_argument("--out-dir")
    args = ap.parse_args(argv)
    root = os.path.abspath(args.root)
    out = os.path.abspath(args.out_dir or os.path.join(root, "docs", "process"))
    graph = seam.build(root)
    for name, content in (("DOCTRINE_INDEX.md", render_index(root, graph)),
                          ("DOCTRINE_GRAPH.md", render_graph(graph))):
        if write_if_changed(os.path.join(out, name), content):
            print(name)
    return 0


if __name__ == "__main__":
    sys.exit(main())
