#!/usr/bin/env python3
"""release-audit.py - grade shipped PRs against the mission, emit a release-note audit.

Implements docs/process/SHIP_AUDIT_RUBRIC.md.

Read-only. Reads git history (squash commit bodies carry the PR description) and
.chump/state.db for outcome linkage. Never calls the GitHub API.

Computes Axis Q (execution quality, 0-15) and the hard gates mechanically.
Emits Axis M (mission vector) only as a PRIOR - filling it in is the grader's job.

Usage:
  scripts/dev/release-audit.py                 # 7d window
  scripts/dev/release-audit.py --since 30d
  scripts/dev/release-audit.py --worksheet     # per-ship grading sheet, M blank
  scripts/dev/release-audit.py --json
"""
import argparse, json, os, re, sqlite3, subprocess, sys
from collections import Counter

NOISE_RE = re.compile(r"coherence sync|^chore\(deps\): bump|^Merge (pull request|branch)", re.I)
PLACEHOLDER_RE = re.compile(r"agent changes \(auto-committed", re.I)          # G1
REWORK_RE = re.compile(r"\b(revert|accidental|regression|re-verify|dropped hunk|reinstate)\b", re.I)  # G2
DEPTH_RE = re.compile(r"\b(smoke|happy-path|happy path|edge|adversarial)\b", re.I)  # G4
COVERAGE_CLAIM_RE = re.compile(r"\b(covered|coverage|fully tested|test(s|ed)? (pass|green))\b", re.I)
GAP_RE = re.compile(r"\b([A-Za-z][A-Za-z-]{2,}-\d+)\b")
PR_RE = re.compile(r"\(#(\d+)\)\s*$")
PREVENTION_RE = re.compile(r"\b(gate|guard|regression test|CI test|prevent|invariant|precheck)\b", re.I)
TEST_FILE_RE = re.compile(r"(scripts/ci/test-|tests?/|_test\.rs|#\[test\])")

MISSION_OUTCOMES = {"MISSION-010", "MISSION-012", "MISSION-032", "COTG", "CHUMPOS",
                    "META-067", "EFFECTIVE-000"}


def sh(*args):
    return subprocess.run(args, capture_output=True, text=True).stdout


def parse_window(s):
    m = re.fullmatch(r"(\d+)\s*([dhw])", s.strip(), re.I)
    if not m:
        return s
    n, unit = int(m.group(1)), m.group(2).lower()
    return f"{n} {'day' if unit=='d' else 'hour' if unit=='h' else 'week'}s ago"


def load_outcomes(repo_root):
    """gap_id -> (outcome_id, evidence).

    Prefers .chump/state.sql (the live, version-controlled registry regenerated by
    the coherence-sync job). The local state.db is a per-node cache and is routinely
    days stale - on 2026-09-22 it held none of the week's gaps, which would have
    silently scored every recent ship as outcome-less.
    """
    sql = os.path.join(repo_root, ".chump", "state.sql")
    text = None
    if os.path.exists(sql):
        text = open(sql, encoding="utf-8", errors="replace").read()
    else:
        text = sh("git", "show", "origin/main:.chump/state.sql") or None
    if text:
        out, gid = {}, None
        # record-level fields sit at exactly 2 spaces; description bodies are deeper,
        # so this cannot be fooled by prose that happens to contain "outcome_id:".
        for line in text.splitlines():
            m = re.match(r"^- id: (\S+)\s*$", line)
            if m:
                gid = m.group(1)
                out.setdefault(gid, ("", ""))
                continue
            if gid:
                mo = re.match(r"^  outcome_id: (\S+)\s*$", line)
                if mo:
                    out[gid] = (mo.group(1), out[gid][1])
        if out:
            return out, sql + " (live registry)"

    for cand in (os.path.join(repo_root, ".chump/state.db"),
                 os.path.expanduser("~/Projects/Chump/.chump/state.db")):
        if os.path.exists(cand) and os.path.getsize(cand) > 0:
            try:
                con = sqlite3.connect(f"file:{cand}?mode=ro", uri=True)
                rows = con.execute(
                    "SELECT id, COALESCE(outcome_id,''), COALESCE(evidence,'') FROM gaps").fetchall()
                con.close()
                return {r[0]: (r[1], r[2]) for r in rows}, cand + " (STALE CACHE)"
            except sqlite3.Error:
                continue
    return {}, None


def collect(since, repo_root):
    raw = sh("git", "log", "origin/main", f"--since={since}",
             "--date=short", "--pretty=format:%H\x1f%s\x1f%cd\x1f%b\x1e")
    ships, noise = [], 0
    for rec in raw.split("\x1e"):
        rec = rec.strip("\n")
        if not rec.strip():
            continue
        parts = rec.split("\x1f")
        if len(parts) < 2:
            continue
        sha, subj = parts[0], parts[1]
        day = parts[2] if len(parts) > 2 else ""
        body = parts[3] if len(parts) > 3 else ""
        if NOISE_RE.search(subj):
            noise += 1
            continue
        ships.append({"sha": sha[:9], "subject": subj, "day": day, "body": body})
    return ships, noise


def grade(ship, outcomes, dup_titles):
    subj, body = ship["subject"], ship["body"]
    full = subj + "\n" + body
    gaps = GAP_RE.findall(subj) or GAP_RE.findall(body)
    gap_id = gaps[0].upper() if gaps else None
    pr = PR_RE.search(subj)
    known = bool(gap_id) and gap_id in outcomes
    outcome, evidence = outcomes.get(gap_id, ("", "")) if gap_id else ("", "")

    norm = re.sub(r"^[A-Za-z][A-Za-z-]*-\d+:\s*", "", subj)
    norm = re.sub(r"\s*\(#\d+\)$", "", norm).strip()

    gates = []
    # G1 no stated intent
    g1 = bool(PLACEHOLDER_RE.search(subj))
    if g1:
        gates.append("G1:no-stated-intent")
    # G2 rework / revert
    g2 = bool(REWORK_RE.search(subj))
    if g2:
        gates.append("G2:rework")
    # G3 duplicate
    g3 = (not g1) and dup_titles.get(norm, 0) > 1
    if g3:
        gates.append("G3:duplicate")
    # G4 coverage claimed without a depth tier
    g4 = bool(COVERAGE_CLAIM_RE.search(full)) and not DEPTH_RE.search(full)
    if g4:
        gates.append("G4:no-depth-tier")

    # ---- Axis Q (0-3 each) ----
    # T traceability: gap id, PR number, outcome link, evidence
    T = 0 if not gap_id else min(3, 1 + bool(pr) + bool(outcome))
    # V verification depth
    if g4:
        V = 0
    elif DEPTH_RE.search(full) and TEST_FILE_RE.search(body):
        V = 3
    elif TEST_FILE_RE.search(body):
        V = 2
    elif DEPTH_RE.search(full):
        V = 1
    else:
        V = 0
    # D durability
    if g2:
        D = 0
    elif PREVENTION_RE.search(body) and TEST_FILE_RE.search(body):
        D = 3
    elif PREVENTION_RE.search(body):
        D = 2
    else:
        D = 1
    # L legibility
    if g1:
        L = 0
    else:
        bl = len(body.strip())
        L = 3 if bl >= 400 else 2 if bl >= 120 else 1
    # W waste
    W = 0 if g3 else (1 if g2 else 3)

    Q = T + V + D + L + W

    # ---- Axis M: PRIOR ONLY ----
    if g1:
        m_prior = None  # unauditable
    elif outcome in MISSION_OUTCOMES:
        m_prior = 2
    elif outcome:
        m_prior = 1
    else:
        m_prior = 0

    ship.update(dict(gap=gap_id, pr=pr.group(1) if pr else None, outcome=outcome,
                     known=known,
                     norm=norm, gates=gates, T=T, V=V, D=D, L=L, W=W, Q=Q,
                     m_prior=m_prior, unauditable=g1))
    return ship


def verdict(s, M):
    if s["gates"]:
        return "DEBT"
    if M is None:
        return "UNAUDITABLE"
    if M >= 2 and s["Q"] >= 11:
        return "SHIP OF RECORD"
    if M >= 2 and s["Q"] >= 8:
        return "SOLID"
    if M == 1 and s["Q"] >= 8:
        return "LIGHTS-ON"
    return "MOTION"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--since", default="7d")
    ap.add_argument("--worksheet", action="store_true")
    ap.add_argument("--json", action="store_true")
    a = ap.parse_args()

    repo_root = sh("git", "rev-parse", "--show-toplevel").strip() or "."
    since = parse_window(a.since)
    outcomes, db = load_outcomes(repo_root)
    ships, noise = collect(since, repo_root)

    dup = Counter()
    for s in ships:
        if PLACEHOLDER_RE.search(s["subject"]):
            continue  # shared placeholder != duplicate work (see G1)
        n = re.sub(r"\s*\(#\d+\)$", "", re.sub(r"^[A-Za-z][A-Za-z-]*-\d+:\s*", "", s["subject"])).strip()
        dup[n] += 1
    graded = [grade(s, outcomes, dup) for s in ships]

    total_commits = len(ships) + noise
    unaud = [s for s in graded if s["unauditable"]]
    debt = [s for s in graded if s["gates"]]
    auditable = [s for s in graded if not s["unauditable"]]
    qs = [s["Q"] for s in auditable]

    if a.json:
        print(json.dumps({"window": since, "db": db, "total_commits": total_commits,
                          "noise": noise, "real_ships": len(ships),
                          "unauditable": len(unaud), "debt": len(debt),
                          "ships": graded}, indent=2))
        return 0

    if a.worksheet:
        print(f"# Ship audit worksheet ({since})")
        print("# Fill in M (0-3) per docs/process/SHIP_AUDIT_RUBRIC.md. m_prior is a PRIOR, not a grade.\n")
        print(f"{'SHA':<10} {'GAP':<16} {'Q':>2} {'prior':>5}  M  GATES / TITLE")
        for s in sorted(graded, key=lambda x: -x["Q"]):
            mp = "-" if s["m_prior"] is None else s["m_prior"]
            g = ",".join(s["gates"]) or ""
            print(f"{s['sha']:<10} {(s['gap'] or '-'):<16} {s['Q']:>2} {mp:>5}  _  {g:<28} {s['subject'][:70]}")
        return 0

    pct = lambda n, d: f"{100*n/d:.0f}%" if d else "n/a"
    print(f"=== RELEASE-NOTE AUDIT ({since}) ===")
    print(f"rubric: docs/process/SHIP_AUDIT_RUBRIC.md   state.db: {db or 'NOT FOUND'}\n")
    print("1. SIGNAL-TO-NOISE")
    print(f"   commits on main : {total_commits}")
    print(f"   automated no-op : {noise}  ({pct(noise, total_commits)})")
    print(f"   real ships      : {len(ships)}  ({pct(len(ships), total_commits)})")
    print("   (any throughput number counting the no-ops is false)\n")

    print("1b. CADENCE (an aggregate over a window that ends in a collapse lies)")
    by_day = Counter(s["day"] for s in ships if s["day"])
    if by_day:
        days = sorted(by_day)
        recent = days[-10:]
        peak = max(by_day[d] for d in days)
        for d in recent:
            n = by_day[d]
            bar = "#" * min(40, n)
            print(f"   {d}  {n:>3}  {bar}")
        last, first = by_day[days[-1]], by_day[days[0]]
        # flag a cliff: last day is <25% of the window peak and the window is long enough
        if len(days) >= 3 and peak >= 4 and last * 4 < peak:
            print(f"   !! CLIFF: last day {last} vs window peak {peak}. "
                  f"The totals above are NOT the current rate.")
    else:
        print("   (no dated ships in window)")
    print()

    print("2. MISSION-SHIP RATIO (Goal 3, target >= 2/3)")
    print("   NOT COMPUTED. Axis M requires a grader to read the diff.")
    linked = [s for s in auditable if s["outcome"]]
    unknown = [s for s in auditable if s["gap"] and not s["known"]]
    nolink = [s for s in auditable if s["gap"] and s["known"] and not s["outcome"]]
    print(f"   traceability floor (what CAN be checked mechanically):")
    print(f"     outcome-linked      : {len(linked)}/{len(auditable)}  ({pct(len(linked), len(auditable))})")
    print(f"     linked to a MISSION : {len([s for s in linked if s['outcome'] in MISSION_OUTCOMES])}")
    print(f"     in registry, no link : {len(nolink)}")
    print(f"     gap not in registry  : {len(unknown)}")
    print("   run --worksheet to grade M, then recompute the real ratio\n")

    print("2b. TEST-DEPTH DISCIPLINE (shop rule 8: green is not covered)")
    td = [s for s in auditable if DEPTH_RE.search(s["subject"] + s["body"])]
    tt = [s for s in auditable if TEST_FILE_RE.search(s["body"])]
    print(f"   mention a test artifact : {len(tt)}/{len(auditable)}  ({pct(len(tt), len(auditable))})")
    print(f"   name a depth tier       : {len(td)}/{len(auditable)}  ({pct(len(td), len(auditable))})\n")

    print("3. EXECUTION QUALITY (Axis Q, 0-15)")
    if qs:
        qs_sorted = sorted(qs)
        print(f"   median Q : {qs_sorted[len(qs_sorted)//2]}   mean Q : {sum(qs)/len(qs):.1f}   n={len(qs)}")
        for dim in "TVDLW":
            vals = [s[dim] for s in auditable]
            print(f"     {dim}: mean {sum(vals)/len(vals):.1f}")
    print()

    print("4. DEBT COLUMN (gates tripped - never omitted)")
    if not debt:
        print("   none")
    else:
        gc = Counter(g for s in debt for g in s["gates"])
        for g, n in gc.most_common():
            print(f"   {g:<24} {n}")
        print(f"   {'TOTAL ships with >=1 gate':<24} {len(debt)}  ({pct(len(debt), len(ships))} of real ships)")
    print()

    print("5. UNAUDITABLE (G1: the error bar on every number above)")
    print(f"   {len(unaud)} ships have no stated intent  ({pct(len(unaud), len(ships))} of real ships)")
    for s in unaud[:5]:
        print(f"     {s['sha']}  {s['subject'][:72]}")
    if len(unaud) > 5:
        print(f"     ... and {len(unaud)-5} more")
    print()

    print("6. THE BINARY")
    print("   run: bash scripts/dev/mission-scoreboard.sh   (section 1)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
