#!/usr/bin/env python3.12
"""Build formal reflection fixture paired to casual_v1 (same task IDs + order).

RESEARCH-026 observer-effect runs two harness passes (formal vs casual). The
cloud harness truncates with --limit from the *start* of the formal file, so
using the full 100-task reflection_tasks.json with limit=50 misaligns with the
50-task casual fixture. This script emits reflection_tasks_formal_paired_v1.json
containing exactly the formal tasks for the IDs in reflection_tasks_casual_v1.json,
in the same order as the casual file.

Usage:
    python3.12 scripts/ab-harness/sync-reflection-paired-formal.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path


def main() -> int:
    root = Path(__file__).resolve().parents[2]
    fix = root / "scripts" / "ab-harness" / "fixtures"
    formal_path = fix / "reflection_tasks.json"
    casual_path = fix / "reflection_tasks_casual_v1.json"
    out_path = fix / "reflection_tasks_formal_paired_v1.json"

    formal = json.loads(formal_path.read_text())
    casual = json.loads(casual_path.read_text())
    by_id = {t["id"]: t for t in formal.get("tasks", [])}
    paired: list[dict] = []
    for t in casual.get("tasks", []):
        tid = t["id"]
        if tid not in by_id:
            print(f"ERROR: casual task id {tid!r} missing from formal fixture", file=sys.stderr)
            return 2
        paired.append(by_id[tid])

    out = {
        "_comment": (
            "Formal arm for RESEARCH-026 — same 50 task IDs and order as "
            "reflection_tasks_casual_v1.json. Generated by "
            "scripts/ab-harness/sync-reflection-paired-formal.py"
        ),
        "variant": "formal_paired_v1",
        "paired_with": "reflection_tasks_casual_v1.json",
        "tasks": paired,
    }
    out_path.write_text(json.dumps(out, indent=2))
    print(f"Wrote {len(paired)} tasks to {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
