//! Checkpoint database operations — save/restore/list conversation snapshots.
//!
//! Phase 1.6 of the Hermes roadmap. The `chump_checkpoints` table is provisioned in
//! [`crate::db_pool`]. Checkpoints record a session id, a human-friendly name, the
//! message count at the time of capture, an optional state snapshot blob, and notes.
//!
//! V1 only persists the metadata + snapshot blob — actual session-state reconstruction
//! is deferred to V2. The tool layer ([`crate::checkpoint_tool`]) calls into here.

use anyhow::Result;

#[derive(Debug, Clone)]
pub struct Checkpoint {
    pub id: i64,
    pub session_id: String,
    pub name: String,
    pub message_count: u32,
    pub state_snapshot_json: Option<String>,
    pub created_at: String,
    pub notes: Option<String>,
}

/// Insert a new checkpoint and return the autogenerated id.
pub fn create_checkpoint(
    session_id: &str,
    name: &str,
    message_count: u32,
    state_snapshot: Option<&str>,
    notes: Option<&str>,
) -> Result<i64> {
    let conn = crate::db_pool::get()?;
    conn.execute(
        "INSERT INTO chump_checkpoints (session_id, name, message_count, state_snapshot_json, notes) \
         VALUES (?1, ?2, ?3, ?4, ?5)",
        rusqlite::params![session_id, name, message_count as i64, state_snapshot, notes],
    )?;
    Ok(conn.last_insert_rowid())
}

/// List all checkpoints for a session, newest first.
pub fn list_checkpoints(session_id: &str) -> Result<Vec<Checkpoint>> {
    let conn = crate::db_pool::get()?;
    let mut stmt = conn.prepare(
        "SELECT id, session_id, name, message_count, state_snapshot_json, created_at, notes \
         FROM chump_checkpoints WHERE session_id = ?1 ORDER BY created_at DESC, id DESC",
    )?;
    let rows = stmt.query_map([session_id], row_to_checkpoint)?;
    rows.collect::<Result<Vec<_>, _>>().map_err(Into::into)
}

/// Fetch a single checkpoint by id.
pub fn get_checkpoint(id: i64) -> Result<Option<Checkpoint>> {
    let conn = crate::db_pool::get()?;
    let mut stmt = conn.prepare(
        "SELECT id, session_id, name, message_count, state_snapshot_json, created_at, notes \
         FROM chump_checkpoints WHERE id = ?1",
    )?;
    let mut rows = stmt.query([id])?;
    if let Some(r) = rows.next()? {
        Ok(Some(row_to_checkpoint(r)?))
    } else {
        Ok(None)
    }
}

/// Delete a checkpoint by id. No-op if it doesn't exist.
pub fn delete_checkpoint(id: i64) -> Result<()> {
    let conn = crate::db_pool::get()?;
    conn.execute("DELETE FROM chump_checkpoints WHERE id = ?1", [id])?;
    Ok(())
}

/// Look up a checkpoint by (session_id, name). Returns the most recent if multiple share a name.
pub fn checkpoint_by_name(session_id: &str, name: &str) -> Result<Option<Checkpoint>> {
    let conn = crate::db_pool::get()?;
    let mut stmt = conn.prepare(
        "SELECT id, session_id, name, message_count, state_snapshot_json, created_at, notes \
         FROM chump_checkpoints WHERE session_id = ?1 AND name = ?2 \
         ORDER BY created_at DESC, id DESC LIMIT 1",
    )?;
    let mut rows = stmt.query(rusqlite::params![session_id, name])?;
    if let Some(r) = rows.next()? {
        Ok(Some(row_to_checkpoint(r)?))
    } else {
        Ok(None)
    }
}

fn row_to_checkpoint(r: &rusqlite::Row) -> rusqlite::Result<Checkpoint> {
    Ok(Checkpoint {
        id: r.get(0)?,
        session_id: r.get(1)?,
        name: r.get(2)?,
        message_count: r.get::<_, i64>(3)? as u32,
        state_snapshot_json: r.get(4)?,
        created_at: r.get(5)?,
        notes: r.get(6)?,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Each test uses a unique session id to avoid clobbering since the pool is shared
    /// across tests within the process.
    fn unique_session(tag: &str) -> String {
        format!(
            "test-cp-{}-{}-{}",
            tag,
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_nanos())
                .unwrap_or(0)
        )
    }

    #[test]
    fn create_and_get_roundtrip() {
        let sid = unique_session("create");
        let id = create_checkpoint(&sid, "before-refactor", 12, Some("{\"ok\":true}"), Some("note"))
            .expect("create");
        let fetched = get_checkpoint(id).expect("get").expect("some");
        assert_eq!(fetched.id, id);
        assert_eq!(fetched.session_id, sid);
        assert_eq!(fetched.name, "before-refactor");
        assert_eq!(fetched.message_count, 12);
        assert_eq!(fetched.state_snapshot_json.as_deref(), Some("{\"ok\":true}"));
        assert_eq!(fetched.notes.as_deref(), Some("note"));
        assert!(!fetched.created_at.is_empty());
    }

    #[test]
    fn list_returns_session_checkpoints_only() {
        let sid_a = unique_session("list-a");
        let sid_b = unique_session("list-b");
        let _ = create_checkpoint(&sid_a, "a1", 1, None, None).unwrap();
        let _ = create_checkpoint(&sid_a, "a2", 2, None, None).unwrap();
        let _ = create_checkpoint(&sid_b, "b1", 1, None, None).unwrap();
        let listed = list_checkpoints(&sid_a).unwrap();
        assert_eq!(listed.len(), 2);
        assert!(listed.iter().all(|c| c.session_id == sid_a));
    }

    #[test]
    fn delete_removes_row() {
        let sid = unique_session("delete");
        let id = create_checkpoint(&sid, "x", 1, None, None).unwrap();
        assert!(get_checkpoint(id).unwrap().is_some());
        delete_checkpoint(id).unwrap();
        assert!(get_checkpoint(id).unwrap().is_none());
    }

    #[test]
    fn checkpoint_by_name_returns_latest() {
        let sid = unique_session("byname");
        let _id1 = create_checkpoint(&sid, "stable", 1, None, None).unwrap();
        // tiny delay so created_at differs at second granularity isn't required —
        // tie-break is `ORDER BY ... id DESC`, so the second insert wins.
        let id2 = create_checkpoint(&sid, "stable", 5, None, Some("newer")).unwrap();
        let found = checkpoint_by_name(&sid, "stable").unwrap().expect("some");
        assert_eq!(found.id, id2);
        assert_eq!(found.message_count, 5);
        assert_eq!(found.notes.as_deref(), Some("newer"));
    }

    #[test]
    fn missing_checkpoint_returns_none() {
        assert!(get_checkpoint(i64::MAX).unwrap().is_none());
        let sid = unique_session("missing");
        assert!(checkpoint_by_name(&sid, "nope").unwrap().is_none());
        assert!(list_checkpoints(&sid).unwrap().is_empty());
    }
}
