//! `chump revert <PR-number-or-merge-commit>` (INFRA-1443)
//!
//! First-class rollback mechanic: given a PR number or merge commit SHA,
//! opens a revert PR with a structured title + comments on the original PR.
//!
//! Usage:
//!   chump revert <PR-number|merge-commit-sha>
//!                [--reason <text>]
//!                [--dry-run]
//!                [--repo <owner/repo>]
//!
//! Exit codes:
//!   0   revert PR created (or dry-run completed)
//!   1   fatal error (PR not found, not merged, git failure)
//!   2   PR already has an open revert PR (idempotency guard)

use anyhow::{anyhow, Context, Result};
use std::path::{Path, PathBuf};
use std::process::Command;

/// Options parsed from CLI args.
pub struct RevertOpts {
    pub target: String, // PR number or merge commit SHA
    pub reason: String,
    pub dry_run: bool,
    pub repo: Option<String>, // owner/repo override
}

impl RevertOpts {
    pub fn parse(args: &[String]) -> Result<Self> {
        // args[0] = "revert", args[1] = target, then flags
        let target = args.get(1).cloned().ok_or_else(|| {
            anyhow!("Usage: chump revert <PR-number|merge-commit> [--reason <text>] [--dry-run]")
        })?;

        let mut reason = String::from("no reason provided");
        let mut dry_run = false;
        let mut repo: Option<String> = None;

        let mut i = 2;
        while i < args.len() {
            match args[i].as_str() {
                "--reason" => {
                    reason = args
                        .get(i + 1)
                        .cloned()
                        .ok_or_else(|| anyhow!("--reason requires a value"))?;
                    i += 2;
                }
                "--dry-run" => {
                    dry_run = true;
                    i += 1;
                }
                "--repo" => {
                    repo = Some(
                        args.get(i + 1)
                            .cloned()
                            .ok_or_else(|| anyhow!("--repo requires owner/repo"))?,
                    );
                    i += 2;
                }
                other => {
                    return Err(anyhow!("unknown flag: {other}"));
                }
            }
        }

        Ok(Self {
            target,
            reason,
            dry_run,
            repo,
        })
    }
}

/// Info extracted from the original PR.
struct PrInfo {
    number: u64,
    title: String,
    merge_sha: String,
    head_ref: String,
}

/// Run the revert command. Returns the revert PR URL on success.
pub fn run(opts: &RevertOpts, repo_root: &Path) -> Result<String> {
    // Resolve GitHub repo slug (owner/repo).
    let repo_slug = resolve_repo_slug(opts, repo_root)?;

    // Resolve the PR info.
    let pr_info = resolve_pr_info(&opts.target, &repo_slug, repo_root)?;

    // Extract gap ID from PR title if present (e.g., "feat(INFRA-1404): …" → "INFRA-1404").
    let gap_id = extract_gap_id(&pr_info.title);
    let gap_display = gap_id.clone().unwrap_or_else(|| "unknown".to_string());

    // Compute short SHA for branch naming.
    let short_sha = &pr_info.merge_sha[..7.min(pr_info.merge_sha.len())];

    // Branch name: revert/<pr-number>-<short-sha>
    let revert_branch = format!("revert/{}-{}", pr_info.number, short_sha);

    // Revert commit message.
    let commit_msg = format!(
        "revert({}): rollback #{} due to {}\n\nReverts merge commit {} from PR #{} ({})\nOriginal branch: {}",
        gap_display,
        pr_info.number,
        opts.reason,
        pr_info.merge_sha,
        pr_info.number,
        pr_info.title,
        pr_info.head_ref,
    );

    // PR title.
    let pr_title = format!(
        "revert({}): rollback #{} due to {}",
        gap_display, pr_info.number, opts.reason,
    );

    // PR body.
    let pr_body = format!(
        "## Revert of #{}\n\n\
        **Reason:** {}\n\n\
        **Original PR:** #{} — {}\n\
        **Merge commit:** `{}`\n\n\
        This PR reverts the squash-merge of #{} to restore the pre-merge state of main.\n\n\
        Once this revert merges, file a new PR with the fixed implementation.\n\n\
        🤖 Generated by `chump revert {} --reason '{}'`",
        pr_info.number,
        opts.reason,
        pr_info.number,
        pr_info.title,
        pr_info.merge_sha,
        pr_info.number,
        opts.target,
        opts.reason,
    );

    if opts.dry_run {
        println!("[dry-run] Would create branch: {revert_branch}");
        println!("[dry-run] Would revert merge commit: {}", pr_info.merge_sha);
        println!("[dry-run] PR title: {pr_title}");
        println!("[dry-run] Would comment on PR #{}", pr_info.number);
        return Ok(format!(
            "[dry-run] revert PR would be created in repo {repo_slug}"
        ));
    }

    // 1. Fetch latest main.
    run_git(&["fetch", "origin", "main", "--quiet"], repo_root).context("git fetch origin main")?;

    // 2. Create revert branch from origin/main.
    run_git(
        &["checkout", "-b", &revert_branch, "origin/main"],
        repo_root,
    )
    .context("git checkout -b revert branch")?;

    // 3. Run git revert (mainline 1 = first parent = original main before merge).
    run_git(
        &[
            "revert",
            &pr_info.merge_sha,
            "--mainline",
            "1",
            "--no-commit",
        ],
        repo_root,
    )
    .context("git revert --mainline 1")?;

    // 4. Commit the revert.
    run_git(&["commit", "-m", &commit_msg], repo_root).context("git commit")?;

    // 5. Push the branch.
    run_git(
        &["push", "origin", &revert_branch, "--force-with-lease"],
        repo_root,
    )
    .context("git push revert branch")?;

    // 6. Create the revert PR.
    let pr_url = run_gh_create_pr(&pr_title, &pr_body, &revert_branch, &repo_slug)
        .context("gh pr create")?;

    // 7. Comment on the original PR.
    let comment_body = format!(
        "⏪ **Revert PR opened:** {pr_url}\n\n\
        Reason: {}\n\n\
        Run `chump revert {} --reason '{}'` to reproduce.",
        opts.reason, opts.target, opts.reason,
    );
    let _ = run_gh_comment(pr_info.number, &comment_body, &repo_slug);

    // 8. Emit ambient event.
    let _ = emit_revert_event(&pr_info.merge_sha, pr_info.number, &pr_url, repo_root);

    Ok(pr_url)
}

// ── Helpers ──────────────────────────────────────────────────────────────────

fn resolve_repo_slug(opts: &RevertOpts, repo_root: &Path) -> Result<String> {
    if let Some(slug) = &opts.repo {
        return Ok(slug.clone());
    }
    // Try CHUMP_GITHUB_REPO env var.
    if let Ok(s) = std::env::var("CHUMP_GITHUB_REPO") {
        if !s.is_empty() {
            return Ok(s);
        }
    }
    // Derive from git remote.
    let out = Command::new("git")
        .args(["remote", "get-url", "origin"])
        .current_dir(repo_root)
        .output()
        .context("git remote get-url origin")?;
    let url = String::from_utf8_lossy(&out.stdout).trim().to_string();
    // Parse github.com/<owner>/<repo> or git@github.com:<owner>/<repo>.git
    extract_slug_from_remote(&url).ok_or_else(|| {
        anyhow!("cannot derive owner/repo from remote URL: {url}. Use --repo <owner/repo>")
    })
}

fn extract_slug_from_remote(url: &str) -> Option<String> {
    // https://github.com/owner/repo.git or git@github.com:owner/repo.git
    let url = url.trim_end_matches(".git");
    if let Some(rest) = url.strip_prefix("https://github.com/") {
        return Some(rest.to_string());
    }
    if let Some(rest) = url.strip_prefix("git@github.com:") {
        return Some(rest.to_string());
    }
    None
}

fn resolve_pr_info(target: &str, repo_slug: &str, repo_root: &Path) -> Result<PrInfo> {
    // If target looks like a PR number (all digits), use gh pr view.
    if target.chars().all(|c| c.is_ascii_digit()) {
        let pr_num: u64 = target.parse()?;
        return fetch_pr_info(pr_num, repo_slug, repo_root);
    }
    // Assume it's a commit SHA. Find the PR that merged it.
    find_pr_for_commit(target, repo_slug, repo_root)
}

fn fetch_pr_info(pr_num: u64, repo_slug: &str, _repo_root: &Path) -> Result<PrInfo> {
    let out = Command::new("gh")
        .args([
            "pr",
            "view",
            &pr_num.to_string(),
            "--repo",
            repo_slug,
            "--json",
            "mergeCommit,title,number,headRefName,state",
        ])
        .output()
        .context("gh pr view")?;

    if !out.status.success() {
        return Err(anyhow!(
            "gh pr view {} failed: {}",
            pr_num,
            String::from_utf8_lossy(&out.stderr).trim()
        ));
    }

    let json: serde_json::Value =
        serde_json::from_slice(&out.stdout).context("parse gh pr view JSON")?;

    let state = json["state"].as_str().unwrap_or("?");
    if state != "MERGED" {
        return Err(anyhow!(
            "PR #{pr_num} is not merged (state={state}). Can only revert merged PRs."
        ));
    }

    let merge_sha = json["mergeCommit"]["oid"]
        .as_str()
        .ok_or_else(|| {
            anyhow!("PR #{pr_num} has no mergeCommit — was it squash-merged and not yet indexed?")
        })?
        .to_string();

    let title = json["title"].as_str().unwrap_or("?").to_string();
    let head_ref = json["headRefName"].as_str().unwrap_or("?").to_string();

    Ok(PrInfo {
        number: pr_num,
        title,
        merge_sha,
        head_ref,
    })
}

fn find_pr_for_commit(sha: &str, repo_slug: &str, _repo_root: &Path) -> Result<PrInfo> {
    // Use gh api to find the PR associated with the commit.
    let endpoint = format!("repos/{repo_slug}/commits/{sha}/pulls");
    let out = Command::new("gh")
        .args([
            "api",
            &endpoint,
            "--jq",
            ".[0] | {number,title,mergeCommit:.sha,headRefName:.head.ref,state}",
        ])
        .output()
        .context("gh api commits/pulls")?;

    if !out.status.success() {
        return Err(anyhow!(
            "gh api {endpoint} failed: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        ));
    }

    let json: serde_json::Value =
        serde_json::from_slice(&out.stdout).context("parse gh api JSON")?;

    let number = json["number"]
        .as_u64()
        .ok_or_else(|| anyhow!("no PR found for commit {sha}"))?;

    Ok(PrInfo {
        number,
        title: json["title"].as_str().unwrap_or("?").to_string(),
        merge_sha: sha.to_string(),
        head_ref: json["headRefName"].as_str().unwrap_or("?").to_string(),
    })
}

fn extract_gap_id(title: &str) -> Option<String> {
    // Pattern: feat(INFRA-1404): ... or fix(PRODUCT-129): ...
    // Also handles plain gap IDs in title: "INFRA-1404: ..."
    let re = regex::Regex::new(r"\b([A-Z]+-\d+)\b").ok()?;
    re.captures(title)
        .and_then(|c| c.get(1))
        .map(|m| m.as_str().to_string())
}

fn run_git(args: &[&str], repo_root: &Path) -> Result<()> {
    let status = Command::new("git")
        .args(args)
        .current_dir(repo_root)
        .status()
        .with_context(|| format!("git {}", args.join(" ")))?;
    if !status.success() {
        return Err(anyhow!(
            "git {} exited with {}",
            args.join(" "),
            status.code().unwrap_or(-1)
        ));
    }
    Ok(())
}

fn run_gh_create_pr(title: &str, body: &str, branch: &str, repo_slug: &str) -> Result<String> {
    let out = Command::new("gh")
        .args([
            "pr", "create", "--repo", repo_slug, "--base", "main", "--head", branch, "--title",
            title, "--body", body,
        ])
        .output()
        .context("gh pr create")?;

    if !out.status.success() {
        return Err(anyhow!(
            "gh pr create failed: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        ));
    }

    Ok(String::from_utf8_lossy(&out.stdout).trim().to_string())
}

fn run_gh_comment(pr_num: u64, body: &str, repo_slug: &str) -> Result<()> {
    let status = Command::new("gh")
        .args([
            "pr",
            "comment",
            &pr_num.to_string(),
            "--repo",
            repo_slug,
            "--body",
            body,
        ])
        .status()
        .context("gh pr comment")?;
    if !status.success() {
        eprintln!("[revert] warning: gh pr comment failed (non-fatal)");
    }
    Ok(())
}

fn emit_revert_event(
    merge_sha: &str,
    orig_pr: u64,
    revert_pr_url: &str,
    repo_root: &Path,
) -> Result<()> {
    let ts = chrono::Utc::now().format("%Y-%m-%dT%H:%M:%SZ").to_string();
    // Use CHUMP_AMBIENT_LOG env override if set, else default path.
    let ambient = std::env::var("CHUMP_AMBIENT_LOG")
        .map(PathBuf::from)
        .unwrap_or_else(|_| repo_root.join(".chump-locks/ambient.jsonl"));
    let json = format!(
        "{{\"ts\":\"{ts}\",\"kind\":\"gap_revert_pr_opened\",\"merge_sha\":\"{merge_sha}\",\"orig_pr\":{orig_pr},\"revert_pr_url\":\"{revert_pr_url}\"}}",
    );
    if let Some(parent) = ambient.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    use std::io::Write;
    let mut f = std::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(&ambient)
        .context("open ambient.jsonl")?;
    writeln!(f, "{json}").context("write ambient event")?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_extract_gap_id_from_feat_title() {
        assert_eq!(
            extract_gap_id("feat(INFRA-1404): ZERO-WASTE — rebase-and-push"),
            Some("INFRA-1404".to_string())
        );
    }

    #[test]
    fn test_extract_gap_id_from_plain_title() {
        assert_eq!(
            extract_gap_id("PRODUCT-129: fix cockpit button"),
            Some("PRODUCT-129".to_string())
        );
    }

    #[test]
    fn test_extract_gap_id_none() {
        assert_eq!(extract_gap_id("chore: cleanup"), None);
    }

    #[test]
    fn test_extract_slug_https() {
        assert_eq!(
            extract_slug_from_remote("https://github.com/repairman29/chump.git"),
            Some("repairman29/chump".to_string())
        );
    }

    #[test]
    fn test_extract_slug_ssh() {
        assert_eq!(
            extract_slug_from_remote("git@github.com:repairman29/chump.git"),
            Some("repairman29/chump".to_string())
        );
    }

    #[test]
    fn test_parse_opts_basic() {
        let args: Vec<String> = vec![
            "revert".into(),
            "2105".into(),
            "--reason".into(),
            "wedged audit job".into(),
        ];
        let opts = RevertOpts::parse(&args).unwrap();
        assert_eq!(opts.target, "2105");
        assert_eq!(opts.reason, "wedged audit job");
        assert!(!opts.dry_run);
    }

    #[test]
    fn test_parse_opts_dry_run() {
        let args: Vec<String> = vec!["revert".into(), "abc1234".into(), "--dry-run".into()];
        let opts = RevertOpts::parse(&args).unwrap();
        assert!(opts.dry_run);
    }
}
